-- الأرصدة الافتتاحية
begin;
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',200.0,0 from pos_customers where name='معمر علي' and phone='0916484798';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',30.0,0 from pos_customers where name='صبري العباني' and phone='0928537762';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',180.0,0 from pos_customers where name='محمد ابوصاع' and phone='0910707817';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',7810.0,0 from pos_customers where name='أحمد يوسف عرعارة' and phone='0923925129';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',400.0,0 from pos_customers where name='عماد بعزيز' and phone='+218934745535';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',180.0,0 from pos_customers where name='عبدالرحمان الولد' and phone='0925183169';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',390.0,0 from pos_customers where name='صلاح خليفة' and phone='0910000912';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',50.0,0 from pos_customers where name='عبد الجواد اعبان' and phone='0924920914';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',0,1100.0 from pos_customers where name='بدر احمد محمد' and phone='0923165903';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',1210.0,0 from pos_customers where name='هيثم فرح' and phone='0925800809';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',270.0,0 from pos_customers where name='ايمن غراري' and phone='0911845784';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',0,578.0 from pos_customers where name='يوسف الشيخ' and phone='0915099168';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',400.0,0 from pos_customers where name='نجاة' and phone='0922305079';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',270.0,0 from pos_customers where name='عبدالعضيم فلت' and phone='0922144743';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',1979.0,0 from pos_customers where name='احمد سعد' and phone='0922591872';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',155.0,0 from pos_customers where name='شعبان / نضال الجديدة*****' and phone='0918383330//0915699437';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',3000.0,0 from pos_customers where name='المهندس ايمن شركة نماء' and phone='0914887344///0910919317';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',2250.0,0 from pos_customers where name='عبد العزيز من طرف عبد الوهاب' and phone='0928510051';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',16.0,0 from pos_customers where name='احمد قمبرلوا' and phone='0912144303';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',16.5,0 from pos_customers where name='سيف الجليدي' and phone='0910427242';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',4000.0,0 from pos_customers where name='احلام الاسود' and phone='0930063867';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',420.0,0 from pos_customers where name='محمد' and phone='0917359092';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',357.0,0 from pos_customers where name='علي عرقيب' and phone='0914101032';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',10.0,0 from pos_customers where name='أسامة صرمان' and phone='0912139692';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',85.0,0 from pos_customers where name='علي شعيب' and phone='0914084141';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',400.0,0 from pos_customers where name='احمد فاضل سوف' and phone='0928807041';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',40.0,0 from pos_customers where name='محمد الشتوي' and phone='0946148599';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',700.0,0 from pos_customers where name='فارز دباب' and phone='0916428723';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',550.0,0 from pos_customers where name='جوهر علي' and phone='0927670255';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',1640.0,0 from pos_customers where name='وليد زاكي الطاهر صرمان' and phone='0925468642';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',900.0,0 from pos_customers where name='حسن' and phone='0913806172';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',200.0,0 from pos_customers where name='محمد الزروق' and phone='0934902227';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',4950.0,0 from pos_customers where name='احمد يوسف' and phone='0911690160';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',800.0,0 from pos_customers where name='عبدالوهاب ابوراص /// الطاهر السلامي' and phone='0922151790';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',1800.0,0 from pos_customers where name='احمد سالم' and phone='0923602022';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',50.0,0 from pos_customers where name='حكيم جراري' and phone='092218004';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',760.0,0 from pos_customers where name='منير اسماعيل' and phone='0915223602';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',100.0,0 from pos_customers where name='مهند البعوي' and phone='0918233591';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',940.0,0 from pos_customers where name='عبد الله الفرجاني' and phone='0912112725';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',1500.0,0 from pos_customers where name='صلاح جالي' and phone='0918652522';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',0,760.0 from pos_customers where name='مصطفي الرايس' and phone='0917777989';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',255.0,0 from pos_customers where name='احسان بن عمر' and phone is null;
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',150.0,0 from pos_customers where name='بشير' and phone='0927174311';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',315.0,0 from pos_customers where name='عبد المهيمن الزناد' and phone='0914993150';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',640.0,0 from pos_customers where name='علي المرغني' and phone='0919018502';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',6540.0,0 from pos_customers where name='عبد المولي عون' and phone='0917550631';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',800.0,0 from pos_customers where name='رياض' and phone='0910200522';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',316.0,0 from pos_customers where name='لطفي الفاندي' and phone='0914728868';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',7874.0,0 from pos_customers where name='ضياء' and phone='0914110026';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',4250.0,0 from pos_customers where name='عمار السباعي' and phone='0915630360';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',10.0,0 from pos_customers where name='حاتم القماطي' and phone='0912118691';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',901.0,0 from pos_customers where name='Ikbal BEN AMOR' and phone='+33661225546';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',700.0,0 from pos_customers where name='احمد الميشوا تصنيع احواض البرسلين' and phone='0912383993';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',100.0,0 from pos_customers where name='طه المشاط' and phone='0929003003';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',862.0,0 from pos_customers where name='عماد بوعزيز' and phone='0021699442350';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',3951.0,0 from pos_customers where name='عبد الوهاب أبو راص' and phone='0912151790';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',17.0,0 from pos_customers where name='إقبال بن الصوي بن عم' and phone='0033661225546';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',845.0,0 from pos_customers where name='Iheb Ben Amor' and phone='0021628642680';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',120.0,0 from pos_customers where name='هيثم البشتي' and phone='0913722868';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',16200.154,0 from pos_customers where name='مجموعة بن عمر' and phone is null;
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',2700.0,0 from pos_customers where name='طارق الرياني' and phone='0913104139';
insert into pos_customer_ledger (customer_id,entry_type,description,debit,credit) select id,'opening','رصيد افتتاحي',31619.75,0 from pos_customers where name='الزبون' and phone='99999';
commit;
