-- استيراد المخزون — الجزء 9/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10006','مجرى 30 سم *6 سم دهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10006','مجرى 30 سم *6 سم دهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30046','طلاء زيتي 700 غ بني لامع',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30049','طلاء زيتي 700 غ بُرْتُقَالِيّ',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30051','طلاء زيتي 850 غ أبيض لامع',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30054','طلاء زيتي 850 غ فضي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30055','طلاء زيتي 850 غ نحاسي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30069','طلاء بخاخ داخلي و خارجي 300 مل رَمَادِي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20018','علاقة مناشف كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30045','رف زجاجي كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30045','رف زجاجي كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30069','كوربة رايحة لسيفون  3"',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30119','رأس قفل بي في سي 9 سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30200','سكينة تغليف 5"',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80323','قصبة دوش مربعة 30 سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80323','قصبة دوش مربعة 30 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30325','عوامة 3/4',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30331','منشار شجر',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30350','مفتاح تي بالمقبض رقم 8',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30353','مفتاح تي بالمقبض رقم 13',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30407','فرشة صاروخ مفتولة  3" 75 مم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30420','حبل نشر 2.5 مم 10 متر',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30447','خيط لينسة',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30449','خيط أحذية 120 غ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30449','خيط أحذية 120 غ',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20596','فلفلة باب  3/4" سن داخلي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30396','قفل شنطة نحاس 63 مم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2395','قرجوطة 16مم *50 م',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2001','قرجوطة 19مم *50 م',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20051','خلاط حوض المطبخ سحاب اسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20051','خلاط حوض المطبخ سحاب اسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80281','كسكاس دوش مربع 200*200 مم مع قصبة ذهبي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80281','كسكاس دوش مربع 200*200 مم مع قصبة ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30056','بونتة 6 * 16سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30056','بونتة 6 * 16سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80500','شطاف ظغط مربع مع طوبو كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80288','مثبت خلاط فردي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50197','مثبت صندوق بتارية مقعد أرضي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50232','بتارية مقعد أرضي تحت في كييس',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50233','بتارية مقعد أرضي تحت في كييس',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50233','بتارية مقعد أرضي تحت في كييس',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30736','لقمة جيدور كروم رقم 10',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1750','فسيبلي " 1/2 أنثى * "1/2 أنثى 30سم سميك',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80451','سماعة دوش مع طوبو كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80324','كسكاس دوش مربع 250*250 مم مع قصبة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80324','كسكاس دوش مربع 250*250 مم مع قصبة كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1213','فسيبلي خلاط مطبخ شجرة (2طرف) "1/2أنثى 50سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1213','فسيبلي خلاط مطبخ شجرة (2طرف) "1/2أنثى 50سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80411','نبلس خلاط دوش مع وردة كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1217','فسيبلي " 1/2 أنثى * "1/2 أنثى 60سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10253','سرفنتينة10 سم * 10 سم كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80460','مصب دوش بدون تحويلة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80460','مصب دوش بدون تحويلة كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30311','مجفف شعر أبيض',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40622','مسطرة دوش زوجية مربعة مع خلاط أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40622','مسطرة دوش زوجية مربعة مع خلاط أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0696','دولاب حمام مع حوض وجه 80 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0696','دولاب حمام مع حوض وجه 80 سم',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM0696','دولاب حمام مع حوض وجه 80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40697','مراية دولاب حمام 80 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40697','مراية دولاب حمام 80 سم',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM40697','مراية دولاب حمام 80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10702','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 أسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10702','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30355','دهان مطاطي عازل أكريليكي  كغ3.5 أبيض',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10329','حنفية 3/4',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10329','حنفية 3/4',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10386','حنفية فردية حوض بلاستك',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10731','سرفنتينة 15 سم * 15 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10731','سرفنتينة 15 سم * 15 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80734','قصبة دوش دائري 40 سم ذهبي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30745','مرايا حمام مع إضاءة لد-طول 80*60 سم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80989','شطاف ظغط مجرح مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80989','شطاف ظغط مجرح مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0404','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0404','وردة كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80747','مخرج شطاف مع علاق أسود',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80748','مخرج شطاف ذهبي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80750','مخرج شطاف أسود',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80761','مخرج شطاف مع علاق أسود',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50766','سيفون حوض الوجه اسود',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50767','سيفون حوض الوجه ذهبي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50808','سيفون حوض الوجه كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50808','سيفون حوض الوجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80816','مخرج شطاف مع علاق أسود',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80825','كسكاس دوش دائري شريحه 250 مم مع قصبة كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1884','فسيبلي " 1/2 أنثى * "1/2 أنثى 40سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30433','قاعدة ماكينة سنفر صاروخ',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10735','طقم اكسسوار ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10735','طقم اكسسوار ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40760','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40760','مسطرة دوش زوجية كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1450','فسيبلي " 1/2 أنثى * "1/2 أنثى 60سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80507','مصب دوش مع تحويلة كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10815','مقعد معلق ملحوم تورنيدو أبيض',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10815','مقعد معلق ملحوم تورنيدو أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30526','طلاء زيتي 850 غ أبيض مطفي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30527','بونتة حديد رقم 4',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30529','بونتة حديد رقم 6',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50534','قاعدة مكيف ابوفارس',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80854','سماعة دوش دائرية مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80854','سماعة دوش دائرية مع طوبو أسود',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'ARSB80854','سماعة دوش دائرية مع طوبو أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10888','حوض مطبخ ستانلس ستيل   80*48 رصاصي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10888','حوض مطبخ ستانلس ستيل   80*48 رصاصي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20913','خلاط حوض المطبخ سحاب أسود مطفي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20913','خلاط حوض المطبخ سحاب أسود مطفي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30935','مرايا حمام مع إضاءة لد 60*80سم اطار كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30936','مرايا حمام مع إضاءة لد كريستال 60*80سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1543','فسيبلي خلاط مطبخ شجرة (2طرف) "1/2أنثى 60سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30544','لصقة دبل فيس 3 سم 5متر',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81009','سماعة دوش مع طوبو كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU51048','سيفون حوض المطبخ راس كبير بالهواية',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81101','قصبة دوش 40 سم كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30064','خلاط شطاف مع شطاف أسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30064','خلاط شطاف مع شطاف أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80125','مخرج شطاف كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10170','مقعد معلق رايملس أبيض',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10170','مقعد معلق رايملس أبيض',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80298','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80298','سماعة دوش مع طوبو كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1420','فسيبلي " 1/2 أنثى * "1/2 أنثى 30سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1420','فسيبلي " 1/2 أنثى * "1/2 أنثى 30سم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30004','موزع صابون ابيض',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30004','موزع صابون ابيض',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20007','كوع 32" لحام',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30006','مثلث 6" 87.5°',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30024','جرجوري 4" * 3"',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30026','رف زاوية زوجي كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30026','رف زاوية زوجي كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30038','ديسكو حديد تنظيف 7" 180 مم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30040','ديسكو طرانجة 14" 350 مم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30043','ديسكو تنظيف 4.5" 115 مم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30044','ديسكو تنظيف 4" 100*6.4*16',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30047','مخفض 4" * 3"',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50055','غسالة أكواب حوض المطبخ',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30096','كلبس كاو رقم 10',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50097','كلبس كاو رقم 12',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50096','كلبس كاو رقم 16',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50098','كلبس كاو رقم 18',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30099','ملعقة 18سم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30152','عصاة مطرقة',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30158','منجل',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30165','عصاة فأس',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30199','سكينة تغليف 3"',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30326','عوامة 3/4',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30345','مقص عنب',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30377','كستولة',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50397','لصقة 0.13 مم * 19 مم * 25 متر',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30417','عصاة ماصة',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30418','عصاة مسحة',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50424','بتارية مقعد أرضي تحت',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50424','بتارية مقعد أرضي تحت',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30431','ڨوانطي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30432','ڨوانطي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30552','فيتي لاميرة 4.2 * 32 (100غ)',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30581','ريتي لياسة حديد 25 سم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30586','سبتة التبجاني',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20598','فلفلة باب  1/2" سن داخلي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20600','كوربة توماتك 32 - 1" سن خارجي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30395','قفل شنطة نحاس 50 مم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30399','زاوية كرسي 20 * 37 * 1 مم (4 قطع)',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2003','قرجوطة 23مم *50 م',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2004','قرجوطة 26مم *50 م',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80031','شطاف ظغط دائري طتش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80031','شطاف ظغط دائري طتش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60032','خلاط شطاف مدفون كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30031','صابونية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30031','صابونية كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0023','صابونية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0023','صابونية كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MF20189','مراية حمام صغيرة بالعلاقة ضد البخار كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MF20189','مراية حمام صغيرة بالعلاقة ضد البخار كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30198','صابون سائل',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30198','صابون سائل',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30017','مفتاح بيبة رقم13مم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30055','رزة باب حديد رقم12',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30061','رزة باب حديد رقم14',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30066','مفك سالب قصير كورة',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50997','لامبة لد 60وات',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20209','تحويلة 4"',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30737','لقمة جيدور كروم رقم 11',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30739','لقمة جيدور كروم رقم 13',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30741','لقمة جيدور كروم رقم 8',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50156','مثبت غطاء مقعد سكة هندي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50156','مثبت غطاء مقعد سكة هندي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0415','وردة أسود 1/2',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20483','حوض وجه فوق الرخام أبيض -40*30 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20483','حوض وجه فوق الرخام أبيض -40*30 سم',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'VP20483','حوض وجه فوق الرخام أبيض -40*30 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60562','خلاط شطاف مدفون كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60562','خلاط شطاف مدفون كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30310','صابونية كروم حساس',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30310','صابونية كروم حساس',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10590','مقعد معلق رايملس رصاصي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10590','مقعد معلق رايملس رصاصي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80599','كسكاس دوش مربع شريحه 250 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80599','كسكاس دوش مربع شريحه 250 مم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20623','خلاط حوض المطبخ سحاب أسود-كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20623','خلاط حوض المطبخ سحاب أسود-كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10715','مجرى 50 سم *7 سم كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB804093','مصب دوش بدون تحويلة',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB88400','طوبو شطاف 120 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB88400','طوبو شطاف 120 سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM56402','رأس سيفوني كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80749','مخرج شطاف ذهبي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80756','مصب دوش بدون تحويلة ذهبي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80762','مخرج شطاف مع علاق ذهبي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80768','رشاش دوش كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80784','طوبو دوش 200سم كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30797','مرايا حمام ضد البخار مع إضاءة لد بالعلاقة اطار أسود 70*70سم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30797','مرايا حمام ضد البخار مع إضاءة لد بالعلاقة اطار أسود 70*70سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10859','خلاط حوض وجه أسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10859','خلاط حوض وجه أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30457','طلاء بخاخ داخلي و خارجي رصاصي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30432','قاعدة ماكينة سنفر6فتحات',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30434','موس فرش قصير معا غيار',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30436','سكينة تغليف يد بلاستك 10"',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20922','علاقة مناشف زوجية كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MO10925','خلاط حوض المطبخ مولة تحلية كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MO10925','خلاط حوض المطبخ مولة تحلية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10926','خلاط حوض المطبخ شجرة مولة كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20733','علاقة ملابس ثلاثية دوران بدون قصبة',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20453','سنيسكا 32" كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10457','سرفنتينة 15 سم * 15 سم كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80506','مخرج شطاف كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30533','سكينة تغليف8 بلستك',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30856','سلة قمامة ذهبي معلقة 5 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30856','سلة قمامة ذهبي معلقة 5 لتر',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AASB30856','سلة قمامة ذهبي معلقة 5 لتر',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30863','حوض مطبخ جرانيت أبيض مطفي79*51 فردي',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30863','حوض مطبخ جرانيت أبيض مطفي79*51 فردي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30937','مرايا حمام مع إضاءة لد80*60سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0967','دولاب حمام -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10968','حوض وجه معلق -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40969','مراية دولاب حمام 60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0971','دولاب حمام -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10972','حوض وجه معلق -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40973','مراية دولاب حمام 60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0975','دولاب حمام -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10976','حوض وجه معلق -60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40977','مراية دولاب حمام 60 سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1991','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA31004','مدور نحاسي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31022','مرايا حمام ضد البخار لد بالعلاقة اطار وردةأسود70*70سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81038','وصلة مسطرة دوش40سم ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB81038','وصلة مسطرة دوش40سم ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81039','وصلة مسطرة دوش40سم أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB81039','وصلة مسطرة دوش40سم أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81046','وصلة مسطرة دوش60 كروم سم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10572','حنفية غسالة  ''''1/2 * ''''3/4 كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81100','قصبة دوش 40 سم كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP11109','فسيبلي " 1/2 أنثى * "3/8 أنثى 60سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81124','شطاف ظغط مربع مع طوبو كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81127','مخرج شطاف بالعلاقة مربع كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81128','مخرج شطاف مربع كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21131','علاقة مناشف كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30094','ورق سنفرة قماش رقم 180',10.5),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80079','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80079','شطاف ظغط دائري مع طوبو كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50215','بتارية مقعد أرضي تحت',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50215','بتارية مقعد أرضي تحت',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1432','فسيبلي خلاط (2طرف) "1/2 أنثى 50سم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1432','فسيبلي خلاط (2طرف) "1/2 أنثى 50سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10452','مجرى 50 سم *6 سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10452','مجرى 50 سم *6 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10455','مجرى 50 سم *8 سم مشبكة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10455','مجرى 50 سم *8 سم مشبكة كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30003','موزع صابون كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30003','موزع صابون كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30033','استوك 10 كغ',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30001','طوبو1'''' 6 متر',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30003','طوبو3'''' 6 متر',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40043','غطاء مقعد أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40043','غطاء مقعد أبيض',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30042','طلاء عاز ل مطاطي  15 كغ',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30098','ملعقة 18سم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30100','ملعقة 20سم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30101','ملعقة 20سم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30127','قفل طلقة 100 مم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30132','قادومة 200 غ',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30146','ڨلوني 20 لتر',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30232','ڨنبالي',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0266','وردة ذهبي',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30321','كولة 473 مل',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10340','كولة خشب 1 كغ',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30501','بونتة 20 * 450 مم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30374','اسمنت ابيض 50كغ',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30024','خلاط حوض المطبخ حائطي كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30024','خلاط حوض المطبخ حائطي كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80246','مصب دوش شلال بدون تحويلة كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80246','مصب دوش شلال بدون تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30063','مفك سالب',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30896','عازل ناري 16 كغ',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30535','ورق سنفرة 9بوصة 6فتحات',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80275','كسكاس دوش مربع 250*250 مم مع قصبة كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40444','غطاء مقعد تركي أبيض',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10446','مجرى 40 سم *8 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10446','مجرى 40 سم *8 سم كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20248','خلاط دوش ذهبي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20248','خلاط دوش ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20524','خلاط دوش كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40589','غطاء مقعد رايملس أبيض',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WA40589','غطاء مقعد رايملس أبيض',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20325','كسكاس ريتي 32غاطس',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1375','فسيبلي " 1/2 ذكر * "1/2 أنثى 50سم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30742','مرايا حمام مع إضاءة لد-طول 90*60 سم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30401','حاملة ورق منظف كلينكس',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30401','حاملة ورق منظف كلينكس',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80760','مصب دوش مع تحويلة أسود',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50405','علبة مكيف',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80826','كسكاس دوش دائري 250 مم مع قصبة كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80826','كسكاس دوش دائري 250 مم مع قصبة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20857','خلاط دوش ذهبي',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10858','خلاط حوض وجه ذهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10858','خلاط حوض وجه ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20860','خلاط دوش أسود',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1877','فسيبلي خلاط مطبخ شجرة (2طرف) "1/2أنثى 60سم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1877','فسيبلي خلاط مطبخ شجرة (2طرف) "1/2أنثى 60سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20894','خلاط حوض المطبخ سحاب كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20894','خلاط حوض المطبخ سحاب كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10896','خلاط حوض وجه شاشة أسود',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10896','خلاط حوض وجه شاشة أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80934','مصب حوض وجه طويل بدون تحويلة كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30737','رف فردي 50 سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30737','رف فردي 50 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80765','وصلة مسطرة دوش30سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80765','وصلة مسطرة دوش30سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB88868','مخرج شطاف مربع بالعلاقة أسود',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB88868','مخرج شطاف مربع بالعلاقة أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30870','حوض مطبخ جرانيت رصاصي60*45 فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30870','حوض مطبخ جرانيت رصاصي60*45 فردي',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30870','حوض مطبخ جرانيت رصاصي60*45 فردي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30871','حوض مطبخ جرانيت رصاصي72*47 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30871','حوض مطبخ جرانيت رصاصي72*47 فردي',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30871','حوض مطبخ جرانيت رصاصي72*47 فردي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81011','طوبو شطاف فلتر1.2م كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50047','خلاط دوش مدفون كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50047','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0233','نبلس "1/2 * "3/8 كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0259','طابة "1/2 مع وردة كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30275','مرايا حمام مع إضاءة لد 80*60 سم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30281','مرايا حمام مع إضاءة لد 80*60 سم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30281','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80477','طوبو دوش 150سم كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80477','طوبو دوش 150سم كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20001','كوع 25" لحام',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80037','سماعة دوش مع طوبو ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80037','سماعة دوش مع طوبو ذهبي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30008','كوربة 6" 45.5°',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10012','سرفنتينة 15 سم * 15 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10012','سرفنتينة 15 سم * 15 سم كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30117','مقص عنب',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30128','قفل طلقة 90 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30129','قفل طلقة 80 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30133','قادومة 100 غ',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30164','سطل بناء',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30179','مزيل صدأ 400 مل',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30204','سكينة تغليف يد خشب 6" 150 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30207','كلاب  7" 175 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30214','كلاب 180 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30233','دليل باب سحاب',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30435','ڨوانطي',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10472','كولة',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30489','مفتاح زڨنالي (9 قطع)',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30497','بونتة 8 * 450 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30499','بونتة 16 * 450 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30535','بينسة فاصل سراميك',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20536','وصلة أتوماتك',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30589','سلسلة ترية (75 سم)',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30604','رزة إصلاح',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30617','قفل درج 32 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30394','قفل شنطة نحاس 25 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0092','مُطوِّل "1/2 * 25كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80185','مخرج شطاف ذهبي',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80185','مخرج شطاف ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0006','قصبة دوش مربعة 30 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0006','قصبة دوش مربعة 30 سم كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30062','صابونية كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30062','صابونية كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30048','خباشة زيتون فليتي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81002','شطاف ضغط مربع مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB81002','شطاف ضغط مربع مع طوبو ذهبي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80191','مخرج شطاف مع علاق كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80191','مخرج شطاف مع علاق كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80404','كسكاس رقبة خلاط متحركة كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1140','فسيبلي " 1/2 أنثى * "1/2 أنثى 80سم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80278','مخرج شطاف مع علاق كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80278','مخرج شطاف مع علاق كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80224','مسكر شطافة "1/2" * "1/2 كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80224','مسكر شطافة "1/2" * "1/2 كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30249','خلاط شطاف مع شطاف ذهبي',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30249','خلاط شطاف مع شطاف ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20275','فلفلة مولة 3/4" سن داخلي',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FE30276','كسكاس 1 نحاس',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10572','خلاط حوض المطبخ شجرة كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10572','خلاط حوض المطبخ شجرة كروم',3.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
