-- استيراد المخزون — الجزء 10/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20620','خلاط حوض المطبخ دبل سحاب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20620','خلاط حوض المطبخ دبل سحاب كروم',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MA20620','خلاط حوض المطبخ دبل سحاب كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10643','مجرى 30 سم *8 سم كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10643','مجرى 30 سم *8 سم كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30673','فرشاة تنظيف مرحاض ذهبي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30673','فرشاة تنظيف مرحاض ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30741','مرايا حمام مع إضاءة لد-عرض 60*90 سم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30499','فرشة طلاء ايطالية رقم60',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB85299','رشاش دوش كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB85300','رشاش دوش كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0403','وردة كروم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0403','وردة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80755','مصب دوش بدون تحويلة أسود',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80759','مصب دوش بدون تحويلة ذهبي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30800','مرايا حمام ضد البخار مع إضاءة لد 80*70 سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30800','مرايا حمام ضد البخار مع إضاءة لد 80*70 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30834','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30834','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20931','خلاط حوض المطبخ سحاب كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20931','خلاط حوض المطبخ سحاب كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA32453','بونتة 8 * 160 مم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30552','زمالطو زيتي  3 كغ  اسود مطفي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80781','شطاف ظغط مربع كبيرمع طوبو كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80781','شطاف ظغط مربع كبيرمع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80849','شطاف ظغط مربع مع طوبو أسود',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80849','شطاف ظغط مربع مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20910','خلاط حوض المطبخ سحاب ذهبي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20910','خلاط حوض المطبخ سحاب ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30545','سكينة تغليف 3"',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT31007','خلاط شطاف مع شطاف كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11008','خلاط حوض وجه طويل كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31102','مرايا حمام مع إضاءة لد60*80 سم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80094','يد شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80094','يد شطاف كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20161','مقعد أرضي ملحوم رصاصي رخامي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20161','مقعد أرضي ملحوم رصاصي رخامي',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20161','مقعد أرضي ملحوم رصاصي رخامي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30274','مرايا حمام مع إضاءة لد 80*60 سم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30274','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10004','مجرى 40 سم *6 سم دهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10004','مجرى 40 سم *6 سم دهبي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10480','مجرى 45سم *7 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10480','مجرى 45سم *7 سم كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20007','علاقة ملابس خماسية',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20007','علاقة ملابس خماسية',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20036','مواسير 25'''' 4 متر',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30066','طلاء بخاخ داخلي و خارجي أسود مطفي',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10471','لصقة فأر',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10585','صليبة ضغط 2 مم (20 قطعة)',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50091','رجسترو مقعد أرضي مائل 7 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50091','رجسترو مقعد أرضي مائل 7 سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30496','طلاء مائي داخلي 18 كغ الكلمنجارو اقتصادي',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80212','مصب بدون تحويلة 18 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80212','مصب بدون تحويلة 18 سم كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0443','مطول 1/2*50 مم كروم',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50397','رأس سيفوني رخامي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50397','رأس سيفوني رخامي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20619','خلاط دوش كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20619','خلاط دوش كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40621','مسطرة دوش زوجية مربعة مع خلاط كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40621','مسطرة دوش زوجية مربعة مع خلاط كروم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'CD40621','مسطرة دوش زوجية مربعة مع خلاط كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10365','كولة فواصل 032',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30442','ورق سنفرة قماش رقم 150',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80462','كسكاس دوش مربع 250 مم  كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80462','كسكاس دوش مربع 250 مم  كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20515','علاقة مناشف كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20515','علاقة مناشف كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30857','حوض مطبخ جرانيت بيج 80*45 زوجي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30857','حوض مطبخ جرانيت بيج 80*45 زوجي',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30867','حوض مطبخ جرانيت أبيض مطفي60*45 فردي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30867','حوض مطبخ جرانيت أبيض مطفي60*45 فردي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30867','حوض مطبخ جرانيت أبيض مطفي60*45 فردي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30875','حوض مطبخ جرانيت أبيض مطفي72*47 فردي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30875','حوض مطبخ جرانيت أبيض مطفي72*47 فردي',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30875','حوض مطبخ جرانيت أبيض مطفي72*47 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30606','ليفة تنضيف ألمنيوم',13.73),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80122','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80122','مخرج شطاف كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0232','مُطوِّل "1/2 * 30 كروم',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0232','مُطوِّل "1/2 * 30 كروم',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1426','فسيبلي " 1/2 أنثى * "3/8 أنثى 40سم',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30029','واي 2" 45°',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30062','كوربة باب 2" 90°',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30064','طابة نهاية خط 2"',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30070','هوَّاية 4"',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30255','كولة 237 مل',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10342','كولة  180غ',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30429','ڨوانطي',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30538','اسطافة 1" (2 قطع)',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30538','اسطافة 1" (2 قطع)',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80396','قصبة دوش دائري 30 سم كروم',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30065','مفك سالب قصير',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30087','دلونتي 1لتر',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30898','ورق تغليف عادي',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50167','وصلة بتارية مدفونة 35 سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50167','وصلة بتارية مدفونة 35 سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80294','مسكر شطافة "1/2" * "1/2 كروم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50231','مثبت صندوق بتارية مقعد أرضي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50231','مثبت صندوق بتارية مقعد أرضي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20476','مقعد أرضي ملحوم مموج  أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20476','مقعد أرضي ملحوم مموج  أبيض',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20476','مقعد أرضي ملحوم مموج  أبيض',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30522','خلاط شطاف كروم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RE10590','حنفية حوض المطبخ شجرة أسود',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10590','حنفية حوض المطبخ شجرة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10363','كولة فواصل 039',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10367','كولة فواصل 003',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50391','سيفون حوض المطبخ رأس كبير',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50429','رأس سيفوني اسود',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA35441','ديسكو جرانيت 4.5'''' 115 مم',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30116','خفاف عتبة',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30866','حوض مطبخ جرانيت رصاصي79*51 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30866','حوض مطبخ جرانيت رصاصي79*51 فردي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30866','حوض مطبخ جرانيت رصاصي79*51 فردي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10804','خلاط حوض وجه كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10804','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80926','مصب دوش نحاس مع تحويلة كروم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80926','مصب دوش نحاس مع تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80931','شطاف ظغط دائري كلاسيكي مع طوبو كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80931','شطاف ظغط دائري كلاسيكي مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10943','حوض وجه معلق -80 سم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0944','دولاب حمام -80 سم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40945','مراية دولاب حمام 80 سم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40097','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40097','مسطرة دوش زوجية كروم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20026','كواردة 32 سن خارجي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20026','كواردة 32 سن خارجي',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30070','طلاء بخاخ داخلي و خارجي بُنِيّ',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20015','علاقة ملابس خماسية دوران',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20015','علاقة ملابس خماسية دوران',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30028','واي 1.5" 45°',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30035','مثلث باب 4"',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30186','لصقة مع مجفف 100 مل',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30187','لصقة مع مجفف 200 مل',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30433','ڨوانطي',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30463','ترمستاتة',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30554','فيتي 3.5 * 25 (100غ)',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50019','رأس سيفوني كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50019','رأس سيفوني كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80186','مخرج شطاف كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80186','مخرج شطاف كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30059','متر 10م',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30996','قطرامينة 15ك مائية سطل بلاستك',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10624','خلاط حوض المطبخ شجرة رصاصي',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10624','خلاط حوض المطبخ شجرة رصاصي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80662','مخرج شطاف مع علاق كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80662','مخرج شطاف مع علاق كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10368','كولة فواصل 007',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50387','مثبت مقعد جانبي بلاستك',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10939','حوض وجه معلق -80 سم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40940','مراية دولاب حمام 80 سم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0941','دولاب حمام -80 سم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP11079','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50201','سيفون حوض الوجه',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50201','سيفون حوض الوجه',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10209','حوض وجه معلق أبيض -60سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10209','حوض وجه معلق أبيض -60سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0268','مخفض أنثى "1/2 "3/8 كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20032','سنيسكا 32" ليفة',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30028','طلاء مائي داخلي 5 كغ أبيض',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0101','وردة كروم',16.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80004','مخرج شطاف كروم بالعلاقة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80004','مخرج شطاف كروم بالعلاقة',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0130','مطول 1/2*20 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0130','مطول 1/2*20 مم كروم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10250','خلاط حوض وجه ذهبي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10250','خلاط حوض وجه ذهبي',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30603','مرايا حمام مع إضاءة لد مع اطار ذهبي 90*70 سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30603','مرايا حمام مع إضاءة لد مع اطار ذهبي 90*70 سم',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'ML30603','مرايا حمام مع إضاءة لد مع اطار ذهبي 90*70 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30398','طلاء عاز ل بلاستيك  13 كغ',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30324','ڨوانطي',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10364','كولة فواصل 024',16.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80813','مصب دوش قصير بتحويلة كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80813','مصب دوش قصير بتحويلة كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30916','رف زاوية زوجي كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30916','رف زاوية زوجي كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30872','حوض مطبخ جرانيت أسود مطفي72*47 فردي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30872','حوض مطبخ جرانيت أسود مطفي72*47 فردي',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30872','حوض مطبخ جرانيت أسود مطفي72*47 فردي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10894','خلاط حوض وجه ذهبي',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10894','خلاط حوض وجه ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20900','خلاط دوش أسود',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20900','خلاط دوش أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50244','مثبت مقعد أرضي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50244','مثبت مقعد أرضي',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80370','سماعة دوش كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80370','سماعة دوش كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30040','طلاء مائي مطفي  18 كغ',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30026','واي 4" 45°',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30055','طوبو2'''' 6 متر',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30160','محشة',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30550','فيتي لاميرة 4.2 * 25 (100غ)',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30555','فيتي 3.5 * 30 (100غ)',17.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50196','مثبت مقعد أرضي',17.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80292','مسكر شطافة "1/2" * "1/2 كروم',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30985','طلاء مائي داخلي 4 كغ أبيض مطفي',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1754','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',17.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40474','غطاء مقعد موطو أبيض',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40474','غطاء مقعد موطو أبيض',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WA40474','غطاء مقعد موطو أبيض',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80815','مسكر شطافة "1/2" * "1/2 أسود',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80815','مسكر شطافة "1/2" * "1/2 أسود',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0773','وصلة مخفض "3/8 ذكر × "1/2 انثى كروم',17.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10828','حوض وجه معلق أسود -60سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10828','حوض وجه معلق أسود -60سم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'VS10828','حوض وجه معلق أسود -60سم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30858','حوض مطبخ جرانيت أسود 80*45 زوجي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30858','حوض مطبخ جرانيت أسود 80*45 زوجي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30858','حوض مطبخ جرانيت أسود 80*45 زوجي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30869','حوض مطبخ جرانيت أسود مطفي60*45 فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30869','حوض مطبخ جرانيت أسود مطفي60*45 فردي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30869','حوض مطبخ جرانيت أسود مطفي60*45 فردي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP11000','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP11000','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',16.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50261','زر بتارية مقعد',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50261','زر بتارية مقعد',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10002','مجرى 50 سم *8 سم كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10002','مجرى 50 سم *8 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30058','طلاء زيتي لماع داخلي و خارجي 100 غ أبيض',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30059','طابة تسليك 4"',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30068','مخفض 6" * 4"',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30322','كولة 237 مل',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30339','ماكينة سلكون',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30490','ماكينة برشام',18.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10616','خلاط حوض وجه ذهبي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10616','خلاط حوض وجه ذهبي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30630','خلاط شطاف مع شطاف 15 سم أسود',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30630','خلاط شطاف مع شطاف 15 سم أسود',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30411','فرشة ايطالية 15*5',18.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30864','حوض مطبخ جرانيت بيج79*51 فردي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30864','حوض مطبخ جرانيت بيج79*51 فردي',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30864','حوض مطبخ جرانيت بيج79*51 فردي',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30868','حوض مطبخ جرانيت بيج60*45 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30868','حوض مطبخ جرانيت بيج60*45 فردي',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30868','حوض مطبخ جرانيت بيج60*45 فردي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80939','مخرج شطاف مع علاق جانبي كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80939','مخرج شطاف مع علاق جانبي كروم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50057','صابونية حوض مطبخ أسود',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50057','صابونية حوض مطبخ أسود',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30323','كولة 118 مل',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30605','رزة إصلاح',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30613','تل ربط مجلفن (2 كغ)',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30117','سكارة باب PVC بيضاء',19.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20767','مخفض 1/2*3/4 كروم',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20212','مخفض خلاط دوش 1/2*3/4',19.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20475','مقعد أرضي ملحوم مربع  أبيض',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20475','مقعد أرضي ملحوم مربع  أبيض',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20475','مقعد أرضي ملحوم مربع  أبيض',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80598','قصبة دوش مربعة 40 سم كروم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80598','قصبة دوش مربعة 40 سم كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30628','خلاط شطاف مع شطاف 15 سم كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30628','خلاط شطاف مع شطاف 15 سم كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30629','خلاط شطاف مع شطاف 15 سم كروم',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30629','خلاط شطاف مع شطاف 15 سم كروم',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MT30629','خلاط شطاف مع شطاف 15 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10647','مجرى 50 سم *8 سم كروم',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MC10647','مجرى 50 سم *8 سم كروم',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0392','منكوطي املس 3/4',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0392','منكوطي املس 3/4',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0393','منكوطي املس1',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0393','منكوطي املس1',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10410','صليبة بيضاء 3ملي',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30844','ماكينة سلكون',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30421','ديسكو خشب 4.5'''' 110 مم',19.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20855','خلاط دوش كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20855','خلاط دوش كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30859','حوض مطبخ جرانيت رصاصي 80*45 زوجي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30859','حوض مطبخ جرانيت رصاصي 80*45 زوجي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30859','حوض مطبخ جرانيت رصاصي 80*45 زوجي',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30873','حوض مطبخ جرانيت بيج72*47 فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30873','حوض مطبخ جرانيت بيج72*47 فردي',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30873','حوض مطبخ جرانيت بيج72*47 فردي',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10893','خلاط حوض وجه كروم',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10893','خلاط حوض وجه كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50541','لصقة 0.13 مم * 19 مم * 25 متر',19.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'APCI40229','مطول 1/2 *10 مم كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'APCI40229','مطول 1/2 *10 مم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0267','وصلة أنثى "1/2 كروم',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20028','كواردة 32 لحام FIRAT',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30060','طلاء زيتي لماع داخلي و خارجي 100 غ أَحْمَر',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30061','تحويلة 4"',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50307','سيفون حوض الوجه كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50307','سيفون حوض الوجه كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20508','طابة نهاية خط حديد 3/4',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30566','زاوية كرسي 30 * 15 * 1.5 مم (4 قطع)',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30588','سلسلة ترية (75 سم)',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SI10138','سلكون  280 غرام أبيض التاج',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SI10138','سلكون  280 غرام أبيض التاج',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30089','دلونتي 1لتر',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30178','سكارة باب PVC خشبي',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30270','رولة طلاء 10 سم ديكور',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50309','سيفون حوض الوجه كروم بلستك',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50309','سيفون حوض الوجه كروم بلستك',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30602','مرايا حمام مع إضاءة لد مع اطار أسود 90*70 سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30602','مرايا حمام مع إضاءة لد مع اطار أسود 90*70 سم',12.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20665','علاقة مناشف زوجية كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20665','علاقة مناشف زوجية كروم',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'PS20665','علاقة مناشف زوجية كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80717','مسكر شطافة "1/2" * "1/2 اسود',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACE20379','قرسيوني راس سخانة فلتي',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0394','كوربة حديد 3/4',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0395','كوربة حديد1',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1812','فسيبلي " 1/2 أنثى * "3/8 أنثى 40سم',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30854','ماكينة سلكون ثقيلة',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0772','نبلس ذكر"1/2 * ذكر"3/8 كروم',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30852','خلاط شطاف مربع مع شطاف 15 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30852','خلاط شطاف مربع مع شطاف 15 سم كروم',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MT30852','خلاط شطاف مربع مع شطاف 15 سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30854','خلاط شطاف دائري مع شطاف 15 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30854','خلاط شطاف دائري مع شطاف 15 سم كروم',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MT30854','خلاط شطاف دائري مع شطاف 15 سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50891','راجع سيفون حوض مطبخ مربع',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10802','خلاط حوض وجه رصاصي',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10802','خلاط حوض وجه رصاصي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10803','خلاط حوض وجه ذهبي',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10803','خلاط حوض وجه ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10806','خلاط حوض وجه أسود مطفي',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10806','خلاط حوض وجه أسود مطفي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20997','مثلث كروم سن داخلي 1/2',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA1003','وصلة أنثى "1/2 كروم',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81012','علاقة سماعة دوش كبيرة متحركة كروم',20.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC51060','طقم تثبيت المرحاض المعلق على الحائط',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC51060','طقم تثبيت المرحاض المعلق على الحائط',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0555','مطول 1/2*40 مم كروم',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20033','سنيسكا 25" ليفة',21.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30027','طلاء مائي داخلي 20 كغ أبيض',21.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30056','طلاء زيتي لماع داخلي و خارجي 100 غ بني',21.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30553','فيتي 3.5 * 20 (100غ)',21.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0524','وردة أسود',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0524','وردة أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20902','خلاط حوض المطبخ مولة أسود مطفي',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20902','خلاط حوض المطبخ مولة أسود مطفي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0927','كوربة ذكر "1/2 * "1/2 مع وردة كروم',21.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10998','حنفية غسالة  ''''1/2 * ''''3/4 كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10998','حنفية غسالة  ''''1/2 * ''''3/4 كروم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30020','مثلث 2"',22.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30048','مخفض 4" * 2"',22.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30191','لصقة سريعة 3 غرام',22.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30495','بونتة 10 * 160 مم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30495','بونتة 10 * 160 مم',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20511','مثلث حديد سن داخلي 1',22.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30551','فيتي لاميرة 4.2 * 19 (100غ)',22.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ACE20210','فلفلة سخانة',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACE20210','فلفلة سخانة',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50819','رأس سيفوني اسود',22.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0420','مخفض طاسة "1/2 "3/8 كروم',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0420','مخفض طاسة "1/2 "3/8 كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30600','مرايا حمام مع إضاءة لد دائرية بالعلاقة مع اطار أسود 70سم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30600','مرايا حمام مع إضاءة لد دائرية بالعلاقة مع اطار أسود 70سم',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'ML30600','مرايا حمام مع إضاءة لد دائرية بالعلاقة مع اطار أسود 70سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30604','مرايا حمام مع إضاءة لد 80*60سم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30604','مرايا حمام مع إضاءة لد 80*60سم',5.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'ML30604','مرايا حمام مع إضاءة لد 80*60سم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50425','سيفون حوض المطبخ',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50425','سيفون حوض المطبخ',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30865','حوض مطبخ جرانيت أسود مطفي79*51 فردي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30865','حوض مطبخ جرانيت أسود مطفي79*51 فردي',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'EG30865','حوض مطبخ جرانيت أسود مطفي79*51 فردي',15.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20904','خلاط حوض المطبخ مولة أسود مطفي',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20904','خلاط حوض المطبخ مولة أسود مطفي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10922','خلاط حوض المطبخ شجرة أسود مطفي',17.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10922','خلاط حوض المطبخ شجرة أسود مطفي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30057','طلاء زيتي لماع داخلي و خارجي 100 غ رمادي فاتح',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30059','طلاء زيتي لماع داخلي و خارجي 100 غ أزرق داكن',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30023','كوربة باب 4" 87.5°',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30189','فوم 300 غرام',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30423','حبل نشر',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30496','بونتة 12 * 160 مم',23.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10413','سرفنتينة 15 سم * 15 سم كروم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10413','سرفنتينة 15 سم * 15 سم كروم',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10655','سرفنتينة 10 سم * 10 سم كروم',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10655','سرفنتينة 10 سم * 10 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10369','كولة فواصل 018',23.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0814','وصلة مخفض خلاط دوش "3/8 ذكر × "1/2 ذكر كروم',23.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10921','خلاط حوض المطبخ شجرة ذهبي',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10921','خلاط حوض المطبخ شجرة ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20920','خلاط حوض المطبخ مولة كروم',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20920','خلاط حوض المطبخ مولة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81070','مسكر شطافة "1/2" * "1/2 ذهبي',23.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50218','بتارية مقعد أرضي ملحوم تحت 28 سم',18.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50218','بتارية مقعد أرضي ملحوم تحت 28 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10294','حنفية غسالة  ''''1/2 * ''''3/4 كروم',24.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30035','استوك 1 كغ',24.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30061','طلاء زيتي لماع داخلي و خارجي 100 غ أَخْضَرُ',24.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30062','طلاء زيتي لماع داخلي و خارجي 100 غ أزرق فاتح',24.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA3370','مسمارخشب رقم 6 (2 كغ)',24.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50030','سيفون حوض الوجه كروم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50030','سيفون حوض الوجه كروم',13.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10203','سرفنتينة 15 سم * 15 سم كروم',13.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10203','سرفنتينة 15 سم * 15 سم كروم',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50633','سقطار لحوض المطبخ أسود85 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50633','سقطار لحوض المطبخ أسود85 سم',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AECU50633','سقطار لحوض المطبخ أسود85 سم',16.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10645','مجرى 40 سم *8 سم أسود',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10645','مجرى 40 سم *8 سم أسود',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30584','فوم 600 غرام',24.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20162','مقعد أرضي ملحوم ذهبي رخامي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20162','مقعد أرضي ملحوم ذهبي رخامي',6.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20162','مقعد أرضي ملحوم ذهبي رخامي',16.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80256','مثبت خلاط زوجي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80256','مثبت خلاط زوجي',20.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30017','كوربة 1.5" - 90°',25.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30060','وصلة 1.5"* 1.5" سن داخلي',25.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30093','ورق سنفرة قماش رقم 120',25.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0240','مخفض أنثى "1/2 "3/8 كروم',25.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1756','فسيبلي " 1/2 أنثى * "3/8 أنثى 50سم',25.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10650','طقم اكسسوار أسود',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10650','طقم اكسسوار أسود',7.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'SA10650','طقم اكسسوار أسود',11.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80660','مخرج شطاف مع علاق كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80660','مخرج شطاف مع علاق كروم',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30953','رولة طلاء 25 سم / 10',25.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20371','مخفض قومه 2',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20371','مخفض قومه 2',27.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30451','ديسكو حديد 9" 230 مم',25.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20899','خلاط دوش كروم',21.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20899','خلاط دوش كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30068','طلاء بخاخ داخلي و خارجي أصفر',26.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30009','كوربة 4" 87.5°',26.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80379','رشاش دوش مربع كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80379','رشاش دوش مربع كروم',16.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30587','سلسلة ترية (1 متر)',26.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10653','سرفنتينة 15 سم * 15 سم أسود',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10653','سرفنتينة 15 سم * 15 سم أسود',4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MC10653','سرفنتينة 15 سم * 15 سم أسود',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30419','استوك 25 كغ',26.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20827','مقعد أرضي ملحوم أبيض',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20827','مقعد أرضي ملحوم أبيض',8.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20827','مقعد أرضي ملحوم أبيض',12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30092','ورق سنفرة قماش رقم 400',26.5),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20035','سنيسكا 25" قصيرة طربوش',27.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20053','مخفض 4" * 1.5"',27.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20456','طبوا مكيف 3/4',27.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30027','واي 3" 45°',28.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30236','تسيلي حديد 10 مم',28.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0093','مُطوِّل "1/2 * 15كروم',28.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30155','ديسكو حديد4 بوصه',28.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30090','مفك دبل جهتين',28.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50191','مثبت مقعد أرضي حرف L',28.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10807','مقعد معلق تورنيدو أبيض',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10807','مقعد معلق تورنيدو أبيض',7.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WS10807','مقعد معلق تورنيدو أبيض',14.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30535','ديسكو سريع4.5 بوصة حديد',28.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20898','خلاط دوش كروم',23.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20898','خلاط دوش كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0235','كوربة أنثى "1/2 كروم',15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0235','كوربة أنثى "1/2 كروم',14.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0236','كوربة ذكر أنثى "1/2 كروم',19.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0236','كوربة ذكر أنثى "1/2 كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20031','كواردة 25 سن داخلي',29.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30021','مثلث 3"',29.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30046','مجمع 2" 1.5" 1.5" 1.5"',29.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30067','حاملة ورق ناعم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30067','حاملة ورق ناعم كروم',25.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50398','لصقة 0.13 مم * 19 مم * 25 متر',29.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20507','طابة نهاية خط حديد 1',29.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30582','مسمار حلقة مفتوح رقم 10 (2 قطع)',29.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
