-- استيراد المخزون — الجزء 6/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80335','مخرج شطاف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80340','مسكر شطافة "1/2" * "1/2 كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80343','مخرج شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40360','رف حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40360','رف حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80362','رقبة خلاط متحركة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80006','سماعة دوش مايك مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1425','فسيبلي " 1/2 أنثى * "1/2 أنثى 80سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1425','فسيبلي " 1/2 أنثى * "1/2 أنثى 80سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1428','فسيبلي " 1/2 أنثى * "3/8 أنثى 60سم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1428','فسيبلي " 1/2 أنثى * "3/8 أنثى 60سم',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10005','مجرى 50 سم *6 سم دهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10005','مجرى 50 سم *6 سم دهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10470','مجرى 55سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10470','مجرى 55سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30005','موزع صابون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30005','موزع صابون كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80821','مصب دوش مع تحويلة أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80821','مصب دوش مع تحويلة أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30015','زمالطو ضد الصدأ 4 كغ أَحْمَر',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30017','زمالطو ضد الصدأ 3 كغ  رصاصي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30020','زمالطو  2.5 كغ أصفر لامع',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30030','دهان مطاطي عازل أكريليكي  كغ13 أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30034','استوك 4 كغ',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB8040','شطاف ظغط مربع مع طوبو ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB8040','شطاف ظغط مربع مع طوبو ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10046','حوض وجه معلق زاوية أبيض 50 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10046','حوض وجه معلق زاوية أبيض 50 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30048','طلاء زيتي 700 غ أزرق داكن',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30029','رف ستاينلس ستيل أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30029','رف ستاينلس ستيل أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30051','موزع صابون سائل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30051','موزع صابون سائل كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80999','كسكاس دوش دائري بالقصبة 11*15 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50061','مطول سيفون حوض الوجه 30سم كروم',10.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50061','مطول سيفون حوض الوجه 30سم كروم',-6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10069','طقم اكسسوار رصاصي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10069','طقم اكسسوار رصاصي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40086','غطاء مقعد أبيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40088','غطاء مقعد موطو أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40088','غطاء مقعد موطو أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30115','منشار خشب 18" 450 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30118','منشار حديد 12"',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30106','مضخة 1/2 حصان',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30122','قفل سرانتي يمين + يسار',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30161','خباشة',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30170','فرشة طلاء 1.5" 38.1 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30180','لصقة كرتون 200',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30183','فرشة طلاء 5" 127 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30196','منفاخ هواء كهربائي 500 وات',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80217','وجه خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80217','وجه خلاط شطاف مدفون كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30218','سكينة تغليف  2.5" 6.5 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30219','سكينة تغليف  2" 5 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30220','سكينة تغليف  1.5" 3.8 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30221','سكينة تغليف  3.5" 9 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30249','ميزان 30 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30254','رأس غاز ظغط',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50258','زر بتريا كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0265','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0265','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80269','شطاف ظغط مجرح مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60276','ستريتشة 2.44 متر',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30304','حاملة ورق ناعم كلينكس رخامي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30320','رأس غاز ظغط',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30347','مفتاح إنجليزي رقم 8',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30348','مفتاح إنجليزي رقم 24',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30354','مطرقة',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80363','كسكاس دوش مربع 300*300 مم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80363','كسكاس دوش مربع 300*300 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30366','كاوية لحام',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30409','عجلة باب سحاب  رقم 120',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30410','عجلة باب سحاب  رقم 80',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30411','عجلة باب سحاب  رقم 100',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30414','مقص بي بي ار',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30415','مقص بي بي ار',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30430','ڨوانطي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30437','خيط تعليم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30452','ڨوانطي محبب',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30461','رأس سخانة بدون ترمستاتة',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30468','كولة رخام 750 مل فازلين شفافة',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30482','موس فرش',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30486','قطاعة 250 مم رقم 10',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30522','ترودي 2.5 * 350 مم (1ممØ)',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30525','موس منشار 12'''' 300 مم (3 قطع)',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30591','مشمع ثقيل 6 * 7',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20597','فلفلة باب  1" سن داخلي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30615','قفل باب سحاب 40 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30616','قفل باب سحاب 30 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30618','قفل درج 22 مم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10385','حوض مطبخ ستانلس ستيل   304 81 *45 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10385','حوض مطبخ ستانلس ستيل   304 81 *45 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10387','حوض مطبخ ستانلس ستيل   304 75 * 45 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10387','حوض مطبخ ستانلس ستيل   304 75 * 45 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80388','شطاف ظغط مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80388','شطاف ظغط مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30393','مجفف شعر أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40081','قاعدة حوض وجه برسلين 90 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40081','قاعدة حوض وجه برسلين 90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10059','خلاط حوض وجه  15 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10059','خلاط حوض وجه  15 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50049','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50049','خلاط دوش مدفون كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80019','مخرج شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50022','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50022','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10075','خلاط حوض وجه أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10075','خلاط حوض وجه أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30008','خلاط شطاف مع شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80139','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80139','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80165','سماعة دوش مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80168','سماعة دوش مع طوبو أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20060','خلاط دوش مع سماعة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20060','خلاط دوش مع سماعة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50027','سيفون حوض الوجه اسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80182','مخرج شطاف مربع بالعلاقة أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0007','كسكاس دوش مربع 200*200 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0007','كسكاس دوش مربع 200*200 مم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30080','طوبو1'''' (1 متر)',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30082','طوبو1.5'''' (1 متر)',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80197','قصبة دوش  40 سم شبشاشة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80197','قصبة دوش  40 سم شبشاشة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80399','سماعة دوش مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10013','مجرى 50 سم *6 سم كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10013','مجرى 50 سم *6 سم كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10020','طقم اكسسوار خزف رباعي أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10020','طقم اكسسوار خزف رباعي أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30056','صابونية كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30057','صابونية زجاجي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30079','صابونية أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30080','حاملة فرشاة أسنان أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0016','طوبو دوش 200سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0024','حاملة فوط كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0024','حاملة فوط كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20139','علاقة مناشف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30157','حاملة فوط أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30157','حاملة فوط أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50179','زر بتريا ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50179','زر بتريا ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20044','حاجز دوش 8 مم  مظلم 120  سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20044','حاجز دوش 8 مم  مظلم 120  سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10047','مجرى 30 سم *6 سم أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30047','مفتاح بيبة رقم 22 مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30016','مفتاح بيبة رقم15مم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30057','متر 5م',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10057','سرفنتينة 15 سم * 15 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10083','مجرى 45سم *7 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10089','مجرى 60سم *7 سم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10091','مجرى خارجي  50 سم *13 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80237','طوبو دوش 175سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80230','وصلة مسطرة دوش50سم ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50966','لامبة لد 40وات',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10113','حوض وجه معلق - يمين -80 * 35 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20115','حوض وجه دائري فوق الرخام - 46سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20115','حوض وجه دائري فوق الرخام - 46سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30164','حاملة فرشاة أسنان',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ADOU50187','سيفون حوض قدم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50210','مثبت غطاء مقعد جانبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50208','مولة عمود حوض الوجه',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20760','علاقة مناشف',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10136','حوض مطبخ ستانلس ستيل   304 60 * 45 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50154','زر بتارية مقعد كبير',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40162','مسطرة دوش زوجية دهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40162','مسطرة دوش زوجية دهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30784','موزع صابون سائل كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20786','حوض وجه فوق الرخام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20786','حوض وجه فوق الرخام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80357','سماعة دوش مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80804','شطاف ضغط دائري مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20809','مقعد أرضي أبيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40172','حوض وجه برسلين مشطوف 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40172','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40173','رف حوض وجه برسلين 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40173','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0208','وردة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10218','حنفية حوض المطبخ شجرة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30419','حوض مطبخ جرانيت رمادي محبب 55*44',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30419','حوض مطبخ جرانيت رمادي محبب 55*44',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80426','مصب دوش مع تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80428','كسكاس دوش دائري 250 مم كروم  مع القصبة',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10429','طقم اكسسوار أسود\كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40235','مسطرة دوش مع خلاط ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40235','مسطرة دوش مع خلاط ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40238','مسطرة دوش مع خلاط  دهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40238','مسطرة دوش مع خلاط  دهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80251','سماعة دوش مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20242','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20242','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20460','خلاط حوض المطبخ سحاب كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80468','مسكر شطافة دبل "1/2" * "1/2 كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20288','حاجز دوش 8 مم بالعلاقة المناشف100 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20288','حاجز دوش 8 مم بالعلاقة المناشف100 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80594','وجه خلاط شطاف مدفون كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80594','وجه خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10594','مقعد معلق تورنيدو أبيض',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WS10594','مقعد معلق تورنيدو أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80611','وجه خلاط شطاف مدفون دائري كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80611','وجه خلاط شطاف مدفون دائري كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80612','وجه خلاط دوش مدفون دائري كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80612','وجه خلاط دوش مدفون دائري كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80613','يد خلاط  مدفون كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80613','يد خلاط  مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80639','مسكر شطافة "1/2" * "1/2 كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80639','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'ARSB80639','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80682','وجه خلاط دوش مدفون مربع كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80682','وجه خلاط دوش مدفون مربع كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10684','خلاط حوض المطبخ شجرة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40691','مراية دولاب حمام 80 سم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM40691','مراية دولاب حمام 80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30713','مورش صابونية دائري',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30789','برايمر كالي 5كجم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AETS20378','تفلون سائل 15ml',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB85499','رشاش دوش ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50399','خلاط دوش مدفون كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60400','خلاط شطاف مدفون كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80453','كسكاس دوش دائري 300 مم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80473','قصبة دوش 35 سم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30413','حاملة فوط كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30398','مرايا حمام مع إضاءة لد مع بخار 60 اطار ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80442','شطاف ضغط  مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80754','مصب دوش بدون تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20781','علاقة مناشف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30425','نايلو تغليف',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30786','مرايا حمام ضد البخار مع إضاءة لد 70*70 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30790','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80807','شطاف ظغط دائري مع طوبو أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80807','شطاف ظغط دائري مع طوبو أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MLE40821','خلاط حوض وجه مدفون ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40821','خلاط حوض وجه مدفون ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20820','علاقة مناشف فردية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20820','علاقة مناشف فردية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50821','خلاط دوش مدفون فلفيت أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50821','خلاط دوش مدفون فلفيت أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60822','خلاط شطاف مدفون شريحة مربع كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60822','خلاط شطاف مدفون شريحة مربع كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SC10832','بوكس زاوية  200*100*80 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30861','خلاط شطاف ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30863','مرايا حمام مع إضاءة لد 60*100 سم عرض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1869','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10874','حوض وجه معلق 80*48سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC1413','مطول كهرباء 4مدخل 5متر',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30416','فيتي 3.5 * 40 (1كيلوا)',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30417','سرية بونتة خشب',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10883','عمود حوض وجه أرضي أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30427','رف زاوية زوجي ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10809','طقم اكسسوار أسود الامونيوم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30424','متر 5م',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30435','موس فرش',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10439','غطاء غرفة تفتيش 60*60 فايبر اسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10440','غطاء غرفة تفتيش 80*80 فايبر اسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20889','حاجز دوش 100 * 190 سم 8مم  أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20889','حاجز دوش 100 * 190 سم 8مم  أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10924','مسكر زاوية  ''''1/2 * ''''1/2 ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30928','خلاط شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0737','دولاب حمام مع حوض وجه 60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0737','دولاب حمام مع حوض وجه 60 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30748','مرايا حمام مع إضاءة لد',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30748','مرايا حمام مع إضاءة لد',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10752','خلاط حوض وجه اسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10752','خلاط حوض وجه اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB0758','سماعة دوش مع طوبو أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40762','مسطرة دوش زوجية كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10790','خلاط حوض وجه أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10790','خلاط حوض وجه أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30794','خلاط شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40750','رف كواريون كوارتز 80سم أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40750','رف كواريون كوارتز 80سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40751','حوض كواريون كوارتز80سم أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40751','حوض كواريون كوارتز80سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30752','مرايا حمام مع إضاءة لد-عرض60*80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30752','مرايا حمام مع إضاءة لد-عرض60*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30443','متر 50 رولينة حديد',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30444','متر 100 رولينة قماش',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30884','زمالطو ضد الصدأ1كغ أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30763','فرشاة تنظيف مرحاض رصاصي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30474','شفاط ابيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80988','كسكاس دوش دائري 250 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80988','كسكاس دوش دائري 250 مم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50504','مطول خلاط شطافة مدفون',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10770','مجرى 50 سم *8 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10770','مجرى 50 سم *8 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20513','علاقة مناشف أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30517','حاملة ورق منظف كلينكس',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0858','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0858','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10841','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10841','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10844','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10844','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40861','حوض كواريون كوارتز100سم أبيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40862','رف كواريون كوارتز 100سم أبيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30882','حوض مطبخ جرانيت بيج78*50 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30882','حوض مطبخ جرانيت بيج78*50 فردي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20892','مقعد عربي أبيض61*51',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80932','شطاف ظغط مربع مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80942','وردة خلاط شطاف مدفون كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80943','وردة خلاط دوش مدفون كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80944','يد خلاط  مدفون كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10933','حوض مطبخ ستانلس ستيل تحت الرخامة 304 75*44 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10985','حوض مطبخ ستانلس ستيل تحت الرخامة 304 50*40*22 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10985','حوض مطبخ ستانلس ستيل تحت الرخامة 304 50*40*22 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME11006','خلاط حوض المطبخ شجرة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81054','اكسسوار خلاط دوش مدفون مربع ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81055','اكسسوار خلاط شطاف مدفون مربع ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30547','رف زاوية كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30548','رف زاوية أسود فردي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10571','حوض وجه معلق 60سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10573','خزانة حمام أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0574','حوض وجه مع دولاب حمام -60 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40575','مراية دولاب حمام -60 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81068','كسكاس دوش مربع 300*300 مم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31086','حاملة فرشاة أسنان كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31087','صابونية كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME11095','خلاط حوض المطبخ شلال شجرة رصاصي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME11096','خلاط حوض المطبخ شلال شجرة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31106','موزع صابون كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21107','علاقة مناشف زوجية كروم متحركة',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA11115','طقم اكسسوار كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31129','رف زاوية زوجي ذهبي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA11134','طقم اكسسوار كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA11135','طقم اكسسوار كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10001','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10001','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10038','خلاط حوض وجه مزخرف طويل كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10038','خلاط حوض وجه مزخرف طويل كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80078','شطاف ظغط مربع مع طوبو أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20006','خلاط حوض المطبخ سحاب كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50040','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50040','خلاط دوش مدفون كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80096','مصب دوش بدون تحويلة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80099','مصب دوش مع تحويلة ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80099','مصب دوش مع تحويلة ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80110','قصبة دوش 35 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80116','مصب دوش مع تحويلة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10188','حوض وجه معلق -60 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10191','حوض وجه معلق -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10191','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20215','حوض وجه فوق الرخام أبيض -50سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20215','حوض وجه فوق الرخام أبيض -50سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10243','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10243','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30257','حوض مطبخ جرانيت أبيض محبب  80*50',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10269','مجرى 33 سم *7 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50283','رأس سيفوني 1 ''''1/4  ''''5 كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80318','مخرج شطاف ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80334','مخرج شطاف مع علاق كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80344','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80349','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80008','سماعة دوش مع طوبو ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80008','سماعة دوش مع طوبو ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80365','سماعة دوش مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80365','سماعة دوش مع طوبو ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80366','سماعة دوش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80376','سماعة دوش مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80376','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10472','حنفية ضغط',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10003','سرفنتينة 15 سم * 15 سم اسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10003','سرفنتينة 15 سم * 15 سم اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80719','مصب دوش مع تحويلة ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80719','مصب دوش مع تحويلة ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30022','زمالطو  2.5 كغ أسود لامع',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30025','زمالطو  2.5 كغ رصاصي لامع',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30044','طلاء زيتي 700 غ أصفر لامع',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30047','طلاء زيتي 700 غ أسود لامع',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30027','رف ستاينلس ستيل أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30027','رف ستاينلس ستيل أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30041','ديسكو خرسانة 9" 230 مم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50058','رقبة خلاط حوض مطبخ أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30071','قفل كورة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20082','علاقة ملابس ثلاثية',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30116','منشار خشب 16" 400 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30107','مضخة 3/4 حصان',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30112','بدل كورة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30124','قفل سرانتي يمين + يسار',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30134','قفل طلقة 90 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30137','قفل طلقة 90 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30166','بالة 1.3 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30167','مسحة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30168','مسحة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30169','فرشة طلاء 1" 25.4 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30195','طوبو رش 3/4 20 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30197','سكينة تغليف 4"',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30206','سكينة تغليف 5.5"',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30223','فرشاة حديد',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50231','ڨويدة 30 متر',5.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
