-- استيراد المخزون — الجزء 1/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30377','اسمنت ابيض 1كغ',-264.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30376','جبس العز 1كغ',-261.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'99999','ملحقات مواد صحية',-15.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'99999','ملحقات مواد صحية',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB0175','طلاء وجه خلاط شطافة',-6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FAB0175','طلاء وجه خلاط شطافة',-4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB0177','طلاء وجه زر بتارية',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FAB0177','طلاء وجه زر بتارية',-5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB0176','طلاء وجه خلاط دوش',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FAB0176','طلاء وجه خلاط دوش',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30090','ورق سنفرة قماش رقم 220',-7.5),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0226','سرفنتينة 15 سم * 15 سم كروم',-5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30557','فيتي 3.5 * 40 (100غ)',-5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80640','مسكر شطافة "1/2" * "1/2 كروم',-12.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80640','مسكر شطافة "1/2" * "1/2 كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50830','سلة تجفيف لحوض المطبخ رصاصي',-5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20782','علاقة مناشف أسود',-5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20084','طوبو3''''(1) متر',-4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30835','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30835','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30836','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40754','حوض وجه كوارتز مع رف مع مراية 80 سم',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80471','مسكر شطافة دبل "1/2" * "1/2 كروم',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30373','لصقة مع مجفف 200 مل',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50097','سيفون حوض المطبخ معا راجع',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50097','سيفون حوض المطبخ معا راجع',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0112','حوض وجه مع دولاب حمام -80 سم',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10113','خزانة حمام أبيض',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30114','مرايا حمام مع إضاءة لد 80*60 سم',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30079','مرايا حمام مع إضاءة لد 90*60 سم',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80498','سماعة دوش مع طوبو كروم',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0736','دولاب حمام مع حوض وجه 60 سم',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10741','خزانة حمام أبيض',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0746','مرايا حمام مع إضاءة لد',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30780','صابونية أسود',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0182','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0182','حوض وجه مع دولاب حمام -80 سم',-3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10200','حوض وجه معلق -80 سم',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10200','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80302','شطاف ظغط مربع كبيرمع طوبو كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40388','حوض وجه برسلين مع رف 65 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40389','حوض وجه برسلين مع رف 60 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30418','مرايا حمام مع إضاءة لد 80*60 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10454','حوض وجه معلق 100 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30010','كوربة 4" 45°',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30159','محشة',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30194','لصقة طلاء 27 مم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30481','بينسة رقم 7',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30548','برشام 4.8  * 12',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30092','حاملة ورق ناعم أسود',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10019','مسكر زاوية  ''''1/2 * ''''1/2 كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0078','دولاب حمام -90 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30099','مرايا حمام مع إضاءة لد سداسية 60*80 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB0100','تصنيع قاعدة برسلين',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FAB0100','تصنيع قاعدة برسلين',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40100','حوض وجه برسلين مشطوف مع رف 60',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80300','مسكر شطافة "1/2" * "1/2 كروم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50505','مطول سيفون حوض الوجه 40سم كروم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PE30274','لصقة مع مجفف 300 مل',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB0559','تصنيع حوض مع قاعدة برسلين',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0664','وردة كروم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30778','حاملة ورق ناعم أسود',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30779','حاملة فرشاة أسنان أسود',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10025','خلاط حوض وجه  20 سم كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20003','خلاط دوش كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20122','خلاط حوض المطبخ سحاب كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50046','خلاط دوش مدفون كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10186','حوض وجه معلق -100 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50203','سيفون حوض المطبخ',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10221','حوض وجه سداسي معلق أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10242','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 أسود',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30248','حوض مطبخ جرانيت أبيض محبب 70*50',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30282','مرايا حمام مع إضاءة لد دائرية 60سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30307','حوض قدم خزف مربع 80*80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40331','حوض وجه برسلين 65 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40331','حوض وجه برسلين 65 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40336','حوض وجه برسلين 100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40359','رف حوض وجه برسلين 65 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40359','رف حوض وجه برسلين 65 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40399','حوض وجه برسلين مع رف 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0416','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0416','حوض وجه مع دولاب حمام -80 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10417','خزانة حمام 120*24*20',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10417','خزانة حمام 120*24*20',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0450','دولاب حمام 100 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40452','مراية دولاب حمام 100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50005','خلاط دوش مدفون مع مصب وقصبة وكسكاس برنزي',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30052','طوبو رش 3/4 40 متر',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30182','رولة طلاء 20 سم / 10',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30334','رولة طلاء 25 سم / 10',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50399','لصقة 0.13 مم * 19 مم * 25 متر',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30532','موس مرش',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30614','تل رخام 2 مم (1كغ)',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10017','حوض مطبخ ستانلس ستيل   304 81*51 كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20013','خلاط دوش كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20020','خلاط دوش مع سماعة كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10095','خلاط حوض وجه كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30037','مجفف شعر ذهبي',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30114','رف زاوية زوجي كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0020','شطاف ظغط مع طوبو كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50150','سلة تجفيف لحوض المطبخ أسود',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50151','سلة تجفيف لحوض المطبخ رصاصي',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30054','حوض قدم مربع اكريليك 90*90*14',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40007','مسطرة دوش زوجية ذهبي',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30087','مرايا حمام مع إضاءة لد 50*70 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40050','مسطرة دوش زوجية كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10107','مسكر زاوية  ''''1/2 * ''''1/2 كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FAB0178','طلاء وجه مسكر بي بي ار',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30242','حوض قدم اكريليك 80*80 مربع بالجنب بالسيفوني',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30753','مرايا حمام مع إضاءة لد مع بخاراطار ذهبي 70سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40782','مسطرة دوش زوجية اسود',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20785','حاجز دوش6مم اطار كروم 70 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SC10167','بوكس مربع  190*120*90 سم كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40195','حوض وجه برسلين مشطوف مع رف 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0200','سيفون حوض المطبخ',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30211','غيار روله صينيه 10سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20435','خلاط دوش كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40236','مسطرة دوش مع خلاط كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40236','مسطرة دوش مع خلاط كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30536','مرايا حمام دائرية مع إضاءة لد 80*80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10548','مسكر زاوية  ''''1/2 * ''''1/2 من غير مطول كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30298','مرايا حمام مع إضاءة لد 80*60 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30581','حوض قدم مستطيل اكريليك 120*80*14',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0695','دولاب مع حوض وجه مع مراية حمام 80 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0358','دولاب حمام 80 سم أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0359','حوض وجه  دولاب حمام -80 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10360','خزانة حمام أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40361','مراية دولاب حمام -80 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10721','حوض مطبخ ستانلس ستيل   304 أسود  65 * 45 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50388','وصلة بتارية مدفونة 22 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30744','مرايا حمام مع إضاءة لد-عرض60*80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0838','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0838','حوض وجه مع دولاب حمام -80 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10839','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10839','خزانة حمام أبيض',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10842','خزانة حمام أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30423','شيمة جبس',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0764','مصب دوش بالتحويلة كروم انحاس',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80793','كسكاس دوش مربع شريحة 250*250 مم مع قصبة كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80522','طوبو شطاف 120 سم كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0825','حوض وجه مع دولاب حمام مع مراية -100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB1064','تصنيع حوض مع قاعدة برسلين',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'FAB1089','تصنيع قاعدة برسلين',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20083','طوبو2''''(1) متر',-0.75),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20120','خلاط حوض المطبخ دبل سحاب أسود',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20120','خلاط حوض المطبخ دبل سحاب أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0456','دولاب حمام 85 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0456','دولاب حمام 85 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40457','مراية دولاب حمام 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40457','مراية دولاب حمام 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10458','حوض وجه معلق 85 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10458','حوض وجه معلق 85 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30021','رف زاوية كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30021','رف زاوية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30064','حاملة فرشاة أسنان كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30064','حاملة فرشاة أسنان كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40147','حوض وجه برسلين 100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40147','حوض وجه برسلين 100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40149','رف حوض وجه برسلين 100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40149','رف حوض وجه برسلين 100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40368','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40368','حوض وجه برسلين مشطوف 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40373','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40373','رف حوض وجه برسلين 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30374','مرايا حمام مع إضاءة لد مع اطار أسود 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30374','مرايا حمام مع إضاءة لد مع اطار أسود 80*60 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10096','مسكر زاوية  ''''1/2 * ''''1/2 كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10096','مسكر زاوية  ''''1/2 * ''''1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0106','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0106','حوض وجه مع دولاب حمام -80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10107','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10107','خزانة حمام أبيض',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30108','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30108','مرايا حمام مع إضاءة لد 80*60 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20119','حوض وجه فوق الرخام 100 سم أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20119','حوض وجه فوق الرخام 100 سم أبيض',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0120','دولاب حمام 100 سم أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0120','دولاب حمام 100 سم أبيض',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30121','مرايا حمام مع إضاءة لد 90 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30121','مرايا حمام مع إضاءة لد 90 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50020','رأس سيفوني حوض الوجه طويل أسود',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50020','رأس سيفوني حوض الوجه طويل أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80341','مصب دوش بدون تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80341','مصب دوش بدون تحويلة كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30199','رف زجاجي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30199','رف زجاجي كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10140','حوض وجه معلق -90 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10140','حوض وجه معلق -90 سم',-2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SI10133','سلكون  280 غرام شفاف',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SI10133','سلكون  280 غرام شفاف',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10432','حوض مطبخ ستانلس ستيل   304 50 * 45 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10432','حوض مطبخ ستانلس ستيل   304 50 * 45 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20480','مقعد أرضي ملحوم مربع أبيض',-1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20480','مقعد أرضي ملحوم مربع أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10504','خلاط حوض وجه  كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10504','خلاط حوض وجه  كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0841','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0841','حوض وجه مع دولاب حمام -80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10812','خزانة حمام بيج',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10812','خزانة حمام بيج',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10002','خلاط حوض وجه ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10009','خلاط حوض وجه أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10011','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10017','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10017','خلاط حوض وجه كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10026','خلاط حوض وجه  15 سم أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10029','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10033','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10041','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10043','خلاط حوض وجه طويل  30 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20002','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20005','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20008','خلاط دوش ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20011','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30059','خلاط شطاف مع شطاف كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80075','شطاف ظغط مربع مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80077','شطاف ظغط دائري مع طوبو ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40099','مسطرة دوش زوجية مربعة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40101','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40110','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20121','خلاط حوض المطبخ سحاب ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20002','خلاط حوض المطبخ سحاب أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10004','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20012','خلاط حوض المطبخ سحاب كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60025','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50029','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20034','خلاط حوض المطبخ سحاب أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20035','خلاط حوض المطبخ سحاب أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60044','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60050','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60051','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80055','كسكاس دوش مربع 250*250 مم مع قصبة ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80060','كسكاس دوش مربع 400*400 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80061','كسكاس دوش مربع 250*250 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80065','كسكاس دوش دائري 300 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80067','كسكاس دوش مربع 250*250 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80100','مصب دوش مع تحويلة أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80108','قصبة دوش مربعة 35 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80115','مصب دوش بدون تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80128','مخرج شطاف مع علاق مع محول كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80129','قصبة دوش 30 سم سقفية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80136','مصب دوش مع تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80138','مصب حوض وجه  22 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10145','خلاط حوض وجه مدفون مع مصب ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80149','مصب دوش مع تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80150','مصب حوض وجه 22 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MLE40153','خلاط حوض وجه مدفون مع مَصَب كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20159','مقعد أرضي ملحوم سداسي أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10163','مقعد معلق رايملس أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10171','مقعد معلق رايملس أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20179','مقعد أرضي ملحوم ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0185','حوض وجه مع دولاب حمام -60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40194','مراية دولاب حمام -60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20198','مقعد أرضي أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20199','مقعد أرضي أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10210','حوض وجه معلق أبيض -45*37سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50212','قرجوطة سيفون حوض الوجه 1.1/4*80 سم',-4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50212','قرجوطة سيفون حوض الوجه 1.1/4*80 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50214','بتارية مقعد أرضي جنب',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50214','بتارية مقعد أرضي جنب',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10219','عمود حوض وجه سداسي أرضي أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10220','عمود حوض وجه سداسي معلق أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40227','مراية دولاب حمام -70 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10238','حوض مطبخ ستانلس ستيل   90*45  كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50246','رجسترو مقعد أرضي مائل 3 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50246','رجسترو مقعد أرضي مائل 3 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10250','حنفية 3/4',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30254','حوض مطبخ جرانيت كريمي 80*50',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30255','حوض مطبخ جرانيت أبيض  80*50',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30256','حوض مطبخ جرانيت رملي محبب 80*50',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10268','سخانة 30 لتر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30279','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30280','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50280','رأس سيفوني أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30285','مرايا حمام مع إضاءة لد مع اطار أسود 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10291','مسكر زاوية  ''''1/2 * ''''1/2 ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30295','حوض قدم زاوية 80*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50299','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80310','مخرج شطاف مع علاق كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40318','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40320','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40322','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40325','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40326','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40327','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40328','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40329','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40341','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40345','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40346','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40349','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40351','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40352','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40353','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40356','رف حوض وجه برسلين 60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40361','حوض وجه برسلين 60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80007','سماعة دوش مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80010','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80368','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40394','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40395','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40397','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40398','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0411','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10412','خزانة حمام 120*24*20',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30413','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10420','خزانة حمام 120*24*20',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0421','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30422','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1427','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1427','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30433','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20440','حاجز دوش 10 مم اطار كروم 90 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20441','حاجز 8 مم اطار ذهبي 100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20442','حاجز دوش 10مم اطار كروم منقط 90 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40445','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40446','رف حوض وجه برسلين 65 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10449','سرفنتينة 15 سم * 15 سم ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10450','مجرى 40 سم 6* سم ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10462','حوض وجه معلق 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0463','دولاب مع مراية حمام 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20474','علاقة مناشف زوجية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80475','طوبو دوش 150سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10479','مجرى 55سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20004','علاقة مناشف زوجية ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20006','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30006','موزع صابون كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30006','موزع صابون كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50006','خلاط دوش مدفون مع مصب وقصبة وكسكاس أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10007','سخانة 80 لتر',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80718','مخرج شطاف مربع بالعلاقة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80823','مصب دوش بدون تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB0824','كسكاس دوش دائري 25سم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50011','رأس سيفوني كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80038','شطاف ظغط مربع مع مخرج بالعلاقة مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40044','مراية دولاب حمام لد -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30038','طلاء مائي عازل للرطوبة 5 كغ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30063','طلاء بخاخ داخلي و خارجي أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10008','حوض مطبخ ستانلس ستيل   304',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40016','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30023','رف زاوية زوجي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30025','رف زاوية زوجي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30042','ديسكو سريع 9" 230 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10040','طقم اكسسوار ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20041','علاقة ملابس رباعية',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30053','طوبو رش 3/4 50 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20049','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30059','حاملة فرشاة أسنان كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30059','حاملة فرشاة أسنان كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30074','مجفف يد أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50083','عوامة صندوق طرد',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30084','مقبض قابل للطي مضاد للانزلاق لكبار السن',1.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
