-- استيراد المخزون — الجزء 2/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30010','صابونية كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30010','صابونية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30106','صندوق عدة بلاستك 14" 37*19.5*18سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30107','صندوق عدة بلاستك 17" 42*22*19.5سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30108','صندوق عدة بلاستك 19" 47*24.5*21.5سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30110','ماصة 1.5 كغ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30113','ملعقة رقم 20',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30110','مضخة ماجن 3/4 حصان ضد التآكل',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30120','ترابنو850 وات',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30121','صاروخ 4.5" 600 وات',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30122','صاروخ 9" 2200 وات',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30123','قفل سرانتي يمين + يسار',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30139','عصاة مكنسة',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30142','سلوم 6 درجات',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30143','سلوم 4 درجات 4 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30145','سلوم 6 درجات 5 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30198','منفاخ هواء كهربائي 600 وات',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50242','سير ربط 4 * 400 مم (100 قطعة)',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80267','مخرج شطاف مربع بالعلاقة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0264','وردة أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30267','مفتاح إنجليزي رقم 10',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60273','ستريتشة 2.50 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60285','ستريتشة 2.44 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60288','ستريتشة 2.44 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60292','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60293','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60294','ستريتشة 2.50 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60295','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60296','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60297','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60298','ستريتشة 2.70 متر',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10301','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60305','ستريتشة 3 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10310','سرفنتينة 15 سم * 15 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20319','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30324','كولة 118 مل',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30332','رولة كروسة 10 سم مع فرشة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80350','قصبة دوش دائرية 30 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30341','حاملة منظفات زوجي كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30341','حاملة منظفات زوجي كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30343','سخانة يدوية 1500 وات',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30343','فرشاة مرحاض كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30381','منقار',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30384','ديسكو جرانيت 4.5'''' 115 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30387','ديسكو خشب 4.5'''' 115 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50400','لصقة 0.13 مم * 50 مم * 25 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30421','حبل نشر 5 مم 10 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30422','حبل 8 مم 10 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30439','ماكينة  لحام بي بي ار',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30457','ليفة مسمار 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30485','موس فرش 18 مم بالغيار',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30487','مفتاح زڨنالي مشرشر (9 قطع)',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30503','بونتة منقار 14 * 250 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50520','لصقة 0.13 مم * 19 مم * 25 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30562','خبور 10 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30575','ريتي لياسة 20 سم * 10 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30580','ريتي لياسة 25 سم * 20 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30592','مشمع ثقيل 3 * 4',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30602','ميزان خيط 500 غرام',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30603','بالة 1.2 متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30370','عصاة بالة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40375','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40371','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40400','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40372','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30369','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30376','مرايا حمام مع إضاءة لد 80*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10382','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10383','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10384','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10386','حوض مطبخ ستانلس ستيل   304 65 * 45 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30013','برميل 20 لتر',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60013','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30089','فيتي نجمة سداسية 4 * 30مم 600 قطعة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10024','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10056','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30025','خلاط شطاف مع شطاف كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30025','خلاط شطاف مع شطاف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30115','مرايا حمام مع إضاءة لد 100*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10116','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0117','دولاب حمام 100 سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20118','حوض وجه فوق الرخام 100 سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60004','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50050','خلاط دوش مدفون أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30006','خلاط شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10009','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20010','خلاط حوض المطبخ سحاب كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50021','رأس سيفوني حوض الوجه طويل ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50022','رأس سيفوني حوض الوجه طويل ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10014','خلاط حوض وجه ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10072','خلاط حوض وجه أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40016','خلاط حوض وجه مدفون مع مَصَب ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40017','خلاط حوض وجه مدفون مع مَصَب أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30019','خلاط شطاف كروم مع شطاف أَبْيَضُ',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50024','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50025','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50026','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60029','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60031','خلاط شطاف مدفون ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80033','شطاف ظغط مع طوبو أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60036','خلاط شطاف مدفون أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80042','مصب دوش مع تحويلة ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20005','خلاط حوض المطبخ سحاب أسود-كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10088','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20025','خلاط دوش ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50134','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20050','خلاط حوض المطبخ سحاب أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10027','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10028','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20017','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20027','خلاط دوش ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SI10136','سلكون  280 غرام شفاف التاج',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SI10136','سلكون  280 غرام شفاف التاج',-5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10025','خلاط حوض المطبخ سخانة فورية شجرة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10090','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10093','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10096','خلاط حوض وجه حساس كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10097','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30014','خلاط شطاف مع شطاف ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30016','خلاط شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20031','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10018','حنفية حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80154','شطاف ظغط دائري مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80158','شطاف ظغط دائري مع مخرج شطاف دبل مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80159','شطاف ظغط دائري مع مخرج بالعلاقة مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80170','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80174','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AMEV50019','سماعة خلاط حوض المطبخ كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80284','كسكاس دوش مربع 200*200 مم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80285','كسكاس دوش مربع 200*200 مم مع قصبة ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80385','كسكاس دوش مربع 250*250 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80390','مصب دوش بدون تحويلة أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80331','مصب دوش مع تحويلة ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80332','مصب دوش مع تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80333','مصب دوش مع تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80342','مصب دوش مع تحويلة طويل كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50024','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50025','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50033','سيفون حوض الوجه بلاستك كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50034','سيفون حوض الوجه ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50035','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80360','قصبة دوش 35 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80146','قصبة دوش مربعة 40 سم ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80192','قصبة دوش مربعة 40 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20085','طوبو4''''(1) متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30039','مجفف شعر أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30041','مجفف شعر أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30042','موزع ورق منظف كلينكس أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30047','موزع ورق منظف كلينكس أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30054','حاملة منظفات كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30058','صابونية ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30061','حاملة فرشاة أسنان ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30069','موزع صابون سائل كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30069','موزع صابون سائل كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30071','صابونية أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30083','موزع صابون سائل خزف',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30088','صابونية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30094','حامل منضفات كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30095','رف زاوية زوجي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30103','موزع صابون ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30104','موزع صابون حساس ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30105','موزع صابون حساس ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30106','موزع صابون حساس ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30107','موزع صابون حساس كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30115','حاملة منظفات زوجي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20118','علاقة مناشف زوجية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30119','حاملة منظفات زوجي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0030','قصبة دوش مربعة 45 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0030','قصبة دوش مربعة 45 سم كروم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20121','علاقة ملابس خماسية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20124','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0039','حامل ورق منظف كلينكس',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20128','علاقة ملابس سداسية ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20130','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20132','علاقة مناشف متحركة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20135','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80188','كسكاس دوش مربع 250*250 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30165','خلاط شطاف مع شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30166','خلاط شطاف مع شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80189','شطاف ظغط مربع مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30167','حاملة فوط أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20169','علاقة ملابس فردي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20175','علاقة ملابس زوجية أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30176','حاملة فوط أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50181','زر بتريا كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10184','خلاط حوض وجه زر كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30195','حاملة منظفات كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20041','حاجز دوش 8 مم  مظلم80  سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80242','مخرج شطاف أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50203','رأس سيفوني رخامي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30050','صباصلي صاروخ 9 بوصة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50055','سيفون حوض الوجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30019','مفتاح بيبة رقم10مم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10056','مجرى 33 سم *10 سم مشبك كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10064','مجرى 20سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30062','مفك دبل جهتين كهرباء',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30135','ترابنو شحن دبل بترية 21فولت',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10074','مجرى 30 سم *6 سم دهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10075','مجرى 40 سم *6 سم دهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80241','كسكاس دوش مربع 200*200 مم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10082','سرفنتينة 15 سم * 15 سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10084','مجرى 45سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10086','مجرى 55سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10087','مجرى 55سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10088','مجرى 55سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10090','مجرى 45سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10094','مجرى 75سم *7 سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10095','مجرى 45سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10096','مجرى 45سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10098','مجرى 45سم *7 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40001','مسطرة دوش زوجية مربعة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30070','مرايا حمام مع إضاءة لد مع بخار 60 اطار ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50001','غسالة أكواب حوض المطبخ',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50001','غسالة أكواب حوض المطبخ',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40006','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40008','مسطرة دوش زوجية اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40012','مسطرة دوش فرديه أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20097','مقعد أرضي بدون صندوق أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50098','صندوق بتارية مقعد أرضي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30995','قطرامينة 13ك زيتيه سطل حديد',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50796','برتولامبه بدون تامينه',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30989','طلاء مائي داخلي 10 كغ أبيض ربع لمعه',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40105','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40106','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30100','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40099','حوض وجه برسلين مشطوف مع رف 80',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40117','غطاء مقعد أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10118','حوض وجه معلق -65 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10122','حوض وجه معلق -100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10126','خلاط حوض وجه 2 فتحات كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10127','مقعد معلق أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30131','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC1109','مطول كهرباء 3مدخل 3متر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC1112','مثلث كهرباء تنائي مداخل',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30133','مرايا حمام مع إضاءة لد 80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AMEV50120','رقبه خلاط مطبخ مع مقبض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10144','خزانة حمام خشبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10145','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40147','مراية دولاب حمام 100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0148','حوض وجه مع دولاب حمام مع خزانة مع مراية -100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20154','حوض وجه فوق الرخام أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30166','رف زاوية  اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80666','كسكاس دوش مربع 250*250 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80286','قصبة دوش مربعة 35 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50168','وصلة بتارية مدفونة مائلة 25 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50168','وصلة بتارية مدفونة مائلة 25 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80994','كسكاس دوش مربع 300*300 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40173','غطاء مقعد تركي أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50174','صندوق طرد معلق',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10188','صليبة  2 مم (250 قطعة)',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ADOU50190','سيفون حوض قدم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30193','حوض مطبخ جرانيت أبيض محبب 90*50',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80293','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80402','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30200','أرضية دوش 54×54 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80204','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30215','حاملة ورق ناعم أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10625','حوض وجه معلق -100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30223','رف زاوية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ADOU50220','لصقة عازلة للماء 3.5 م*2.8 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10224','سخانة 50 لتر عمودية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'BAI10238','حوض استحمام بانيو 120*70*55 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20239','خلاط دوش  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30295','دهان عازل خارجي داخلي كغ3.5 أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30935','متر 7.5م',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30243','حوض قدم اكريليك 90*90 زاوية بالجنب بالسيفوني',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10137','حوض مطبخ ستانلس ستيل   304 70 * 45 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80141','مصب دوش قصير بتحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40774','غطاء مقعد أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40776','غطاء مقعد أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30778','حوض قدم خزف مربع 80*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80966','قصبة دوش غلطة سباك',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20787','علاقة مناشف مع قاعدة كروم لامع',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20790','علاقة ملابس فردية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30791','رف زاوية  اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10792','مقعد معلق أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30795','سلة قمامة حمام',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50797','رأس سيفوني كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20800','علاقة ملابس سداسية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10802','مجرى 30 سم *6 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80869','كسكاس دوش دائري 250 مم دهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40176','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40177','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40184','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40189','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40190','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PSB10824','دولاب حمام حوض مع مرايا لد -90 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50820','رأس سيفوني ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50201','زر بتريا اسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80372','كسكاس دوش مربع  250*250 مم اسود مع قصبة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0405','دولاب حمام أرضي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30214','شفاط ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10406','حنفية غسالة  ''''1/2 * ''''3/4 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30410','خلاط حوض المطبخ حائطي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80414','مصب دوش مع تحويلة أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10219','حنفية غسالة  ''''1/2 * ''''3/4 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50422','رأس سيفوني كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50424','رأس سيفوني ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10426','طقم اكسسوار أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80432','مخرج شطاف مع علاق ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10430','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30434','خلاط شطاف مع شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10436','خلاط حوض وجه  20 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10233','طقم اكسسوار دهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40239','مسطرة دوش مع خلاط  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80852','وجه خلاط دوش مدفون',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0252','مقبض خلاط فيوري',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40448','مسطرة دوش زوجية كروم',1.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
