-- استيراد المخزون — الجزء 7/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50240','سير ربط 7.2 * 400 مم (100 قطعة)',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30244','مكنسة 40 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80265','سماعة دوش مع طوبو أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60272','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60274','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60275','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60277','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60278','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60279','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60280','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60281','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60282','ستريتشة 2.44 متر',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0287','وردة ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0287','وردة ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10341','كولة خشب 4 كغ',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30357','ديسكو جرانيت 7'''' 180 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30358','ديسكو جرانيت 9'''' 230 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30360','ديسكو جرانيت 9'''' 230 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30361','شاڨور',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30364','متر 3م',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30368','مكارة رفع رقم 18',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30372','فرطاسة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30373','حاملة إسمنت',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30375','كستولة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30380','منقار',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30389','ديسكو جرانيت 7'''' 180 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30405','فرشة صاروخ نحاس  5" 125 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50425','بتارية مقعد أرضي جنب',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30460','رأس سخانة بدون ترمستاتة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30464','عدة رقعة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30504','بونتة مكيف طاسة كاملة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50518','لصقة خزان 5 سم 5 متر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30524','موس منشار 12'''' 300 مم (10 قطع)',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30527','فلوكة سخانة',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10529','باسطة 240 غ',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10599','مطول مع مسكر  ''''1/2 * ''''1/2',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30369','عصاة مطرقة',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50368','طابة حوض الوجه',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50368','طابة حوض الوجه',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50390','رأس سيفوني رخامي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50390','رأس سيفوني رخامي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2006','قرجوطة 40مم *25 م',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2007','قرجوطة 50مم *25 م',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40082','رف حوض وجه برسلين 90 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40082','رف حوض وجه برسلين 90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10021','خلاط حوض المطبخ شجرة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30026','خلاط شطاف مع شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50023','رأس سيفوني كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50023','رأس سيفوني كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30018','خلاط شطاف كروم مع شطاف',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80043','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10082','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10082','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MI10135','مراية تجميل مع اكسوار',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80153','شطاف ظغط دائري مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80153','شطاف ظغط دائري مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80161','شطاف ظغط دائري مع طوبو رصاصي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80021','مصب دوش بدون تحويلة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80021','مصب دوش بدون تحويلة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80183','مخرج شطاف ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80183','مخرج شطاف ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10021','طقم اكسسوار خزف ثلاثي رصاصي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10021','طقم اكسسوار خزف ثلاثي رصاصي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10048','مجرى 40 سم *10 سم  مشبك كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30051','قشارة أسلاك كهرباء',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB3105','رف زجاجي كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'TO9051','مفتاح ربط رقم 8 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'TO9052','مفتاح ربط رقم14 مم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB82067','سماعة دوش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10067','سرفنتينة 15 سم * 15 سم بلاستك',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10073','سرفنتينة 20*20*28 سم مثلث مشبك كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50870','سيفون حوض الوجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80770','مصب دوش بدون تحويلة متحرك دهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30075','مرايا حمام مع إضاءة لد 80*60 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10076','خزانة حمام أبيض',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0077','حوض وجه مع دولاب حمام -80 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50095','لامبة لد 15 وات',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40112','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40112','حوض وجه برسلين مشطوف 80 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40102','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40102','رف حوض وجه برسلين 80 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10111','سرفنتينة 13 سم * 13 سم كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10119','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10119','حوض وجه معلق -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA33118','محقن بلاستك 13سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80268','مصب دوش طويل بدون تحويلة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80268','مصب دوش طويل بدون تحويلة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80499','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80499','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10183','سرفنتينة 15 سم * 15 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AETS20237','تفلون 19 مم * 30 متر * 0.8 مم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0132','وردة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0132','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80757','شطاف ظغط مربع مع طوبو ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30762','رف زاوية كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20151','علاقة ملابس خماسية دوران',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20153','علاقة ملابس ثلاثية دوران بدون قصبة',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PSB10823','دولاب حمام حوض مع مرايا لد -90 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PSB10823','دولاب حمام حوض مع مرايا لد -90 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50426','سيفون حوض الوجه اسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80326','مصب دوش بدون تحويلة أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80431','كسكاس دوش مربع  300*300 مم كروم مع قصبة',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80601','مصب دوش مع تحويلة ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10433','حوض مطبخ ستانلس ستيل 76*45 سم أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30245','خلاط شطاف مع شطاف أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30245','خلاط شطاف مع شطاف أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20461','خلاط حوض المطبخ سحاب كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80463','سماعة دوش كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20471','علاقة مناشف زوجية كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30473','رف زاوية ثلاثي كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10267','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10267','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30272','طلاء بخاخ داخلي و خارجي ازرق',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80527','شطاف ظغط دائري مع طوبو أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50291','مطول خلاط دوش مدفون',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50291','مطول خلاط دوش مدفون',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80552','سماعة دوش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30301','فرشة مرحاض كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30353','فرشة مرحاض كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40656','مسطرة دوش زوجية مع خلاط دجتل رصاصي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40656','مسطرة دوش زوجية مع خلاط دجتل رصاصي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10321','حوض وجه معلق -130 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10321','حوض وجه معلق -130 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0322','وردة كروم  1/2',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0322','وردة كروم  1/2',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50327','برتولامبه مقلد',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50730','سيفون حوض الوجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80732','كسكاس دوش مربع 300*300 مم ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50398','رأس سيفوني ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80483','مصب دوش بتحويلة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80483','مصب دوش بتحويلة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80415','مخرج شطاف مع علاق كروم معا مسكر',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80456','قصبة دوش 30 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80446','قصبة دوش 40 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB87516','قصبة دوش مربعة 40 سم دهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30397','مرايا حمام مع إضاءة لد مع بخار 60 اطار ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50778','سيفون حوض الوجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80435','سماعة دوش مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10855','مجرى 30 سم *6 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10855','مجرى 30 سم *6 سم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10856','مجرى 40 سم *6 سم كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10872','حوض وجه معلق -60 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30415','فيتي 3.5 * 30 (1كيلوا)',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50431','سيفون حوض المطبخ',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10899','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10438','غطاء غرفة تفتيش 50*50 فايبر اسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80909','كسكاس دوش مربع 300*200 مم مع قصبة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80910','كسكاس دوش مربع 300*200 مم مع قصبة ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20917','حاجز دوش 100 * 190 سم 8مم اطار أسود مخطط',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20917','حاجز دوش 100 * 190 سم 8مم اطار أسود مخطط',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50938','سيفون حوض الوجه بلاستك كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0740','دولاب حمام مع حوض وجه 80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0740','دولاب حمام مع حوض وجه 80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40755','مسطرة دوش زوجية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40755','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80764','سماعة دوش مع طوبو ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10781','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10785','خلاط حوض وجه  كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10785','خلاط حوض وجه  كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10792','خلاط حوض وجه  ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10792','خلاط حوض وجه  ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30751','مرايا حمام مع إضاءة لد-عرض60*80 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30751','مرايا حمام مع إضاءة لد-عرض60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50761','زر بتريا كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80767','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80479','قصبة دوش 40 سم سقفية ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20469','سنيسكا 25" اسود دائري',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30242','رولة كروسة 10 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80505','مخرج شطاف كروم بالعلاقة',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80505','مخرج شطاف كروم بالعلاقة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40508','مسطرة دوش زوجية كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10514','حوض وجه معلق -50 سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20516','علاقة ملابس ثلاثية',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80796','كسكاس دوش دائري شريحة 250*250 مم مع قصبة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50791','رأس سيفوني كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80519','كسكاس دوش مربع مع قصبة 250*250 مم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10522','خلاط حوض وجه  كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0826','دولاب حمام مع إضاءة لد-100 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0826','دولاب حمام مع إضاءة لد-100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10825','حوض وجه معلق -100 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10825','حوض وجه معلق -100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30824','مرايا حمام مع إضاءة لد 100*70 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30824','مرايا حمام مع إضاءة لد 100*70 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30831','سلة قمامة كروم معلقة 5 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30831','سلة قمامة كروم معلقة 5 لتر',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AASB30831','سلة قمامة كروم معلقة 5 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30833','سلة قمامة ذهبي   8 لتر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30833','سلة قمامة ذهبي   8 لتر',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AASB30833','سلة قمامة ذهبي   8 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30834','سلة قمامة أسود  8 لتر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30834','سلة قمامة أسود  8 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0843','حوض وجه مع دولاب حمام -60 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0843','حوض وجه مع دولاب حمام -60 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10840','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10840','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30839','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30839','مرايا حمام مع إضاءة لد80*60 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30842','مرايا حمام مع إضاءة لد80*60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30842','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30880','حوض مطبخ جرانيت رصاصي50*43 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30880','حوض مطبخ جرانيت رصاصي50*43 فردي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30948','مرايا حمام مع إضاءة لد 60*80سم اطار كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30949','مرايا حمام مع إضاءة لد 80*60سم طول اطار كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0959','دولاب حمام -70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10960','حوض وجه معلق -70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40961','مراية دولاب حمام 70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0963','دولاب حمام -70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10964','حوض وجه معلق -70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40965','مراية دولاب حمام 70 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30983','مرايا حمام مع إضاءة لد-عرض60*90 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11014','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML11014','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81015','علاقة سماعة دوش كبيرة متحركة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM51033','سيفون حوض الوجه كلك بمانع رائحة',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM51034','سيفون حوض الوجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81036','كسكاس دوش دائري 250*250 مم مع قصبة اسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM51037','رأس سيفوني ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30557','خلاط شطاف مع شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81066','سماعة دوش مع طوبو ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81067','مصب دوش مع تحويلة ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11069','حوض وجه موطو مع عمود أبيض',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81072','كسكاس دوش مربع 300*300 مم مع قصبة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11090','خلاط حوض وجه كلاسيكي أسود-كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11092','خلاط حوض وجه أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11093','خلاط حوض وجه برنزي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11094','خلاط حوض وجه كلاسيكي كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA11114','طقم اكسسوار كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21116','علاقة مناشف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21117','علاقة مناشف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21118','علاقة مناشف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21119','علاقة مناشف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31120','رف زاوية زوجي كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31123','رف زاوية زوجي كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11139','حوض وجه معلق 60سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11140','حوض وجه معلق 80سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11141','حوض وجه معلق80 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11142','حوض وجه معلق60 سم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10018','خلاط حوض وجه كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10036','خلاط حوض وجه طويل أسود برنزي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10036','خلاط حوض وجه طويل أسود برنزي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30060','خلاط شطاف كروم مع شطاف',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80070','شطاف ظغط مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80092','يد شطاف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80092','يد شطاف كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80093','يد شطاف كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80093','يد شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10131','خلاط حوض المطبخ سحاب أسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20015','خلاط حوض المطبخ سحاب كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10023','حنفية حوض المطبخ شجرة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10023','حنفية حوض المطبخ شجرة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80068','مصب دوش بدون تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80068','مصب دوش بدون تحويلة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80123','مخرج شطاف كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10177','مقعد معلق ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10177','مقعد معلق ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10187','حوض وجه معلق -50 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10187','حوض وجه معلق -50 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10207','حوض وجه معلق أسود -60سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10207','حوض وجه معلق أسود -60سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10241','حوض مطبخ ستانلس ستيل نص منظومة  304 75*45 أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10241','حوض مطبخ ستانلس ستيل نص منظومة  304 75*45 أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10271','مجرى 60 سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10271','مجرى 60 سم *7 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10287','مسكر زاوية  ''''1/2 * ''''1/2 كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10287','مسكر زاوية  ''''1/2 * ''''1/2 كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ADOU50323','كروم M3/4'''' M1/2''''  M1/2'''' محول مسطرة دوش',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ADOU50323','كروم M3/4'''' M1/2''''  M1/2'''' محول مسطرة دوش',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80338','مخرج شطاف كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1424','فسيبلي " 1/2 أنثى * "1/2 أنثى 40سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1429','فسيبلي " 1/2 ذكر * "1/2 أنثى 40سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1431','فسيبلي " 1/2 ذكر * "1/2 أنثى 60سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20009','علاقة مناشف كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50010','رأس سيفوني اسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30024','زمالطو  2.5 كغ بُنِي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30029','طلاء  أكريليكي عازل رطوبة داخل خارج  10 كغ أبيض',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30053','طلاء زيتي ضد الصدأ 850 غ رصاصي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30054','ميزان ألمنيوم 30 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50056','صابونية حوض مطبخ كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50056','صابونية حوض مطبخ كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30114','منشار خشب 16" 400 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30125','قفل طلقة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30126','قفل طلقة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30135','قفل طلقة 80 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30136','قفل طلقة 90 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30174','فرشة طلاء 6" 152.4 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30202','سكينة تغليف يد خشب 5" 300 مم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80216','وجه خلاط دوش مدفون',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80216','وجه خلاط دوش مدفون',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50227','ڨويدة 5 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50228','ڨويدة 10 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50229','ڨويدة 15 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50230','ڨويدة 20 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30234','دليل باب سحاب',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10257','مجرى 40 سم *6 سم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10257','مجرى 40 سم *6 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80259','مصب دوش بدون تحويلة أسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80261','مصب دوش مع تحويلة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80261','مصب دوش مع تحويلة أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80266','مخرج شطاف مربع بالعلاقة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80266','مخرج شطاف مربع بالعلاقة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60271','ستريتشة 2.44 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30327','عوامة 1',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30330','منشار شجر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30343','مقص عنب',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30344','مقص عنب',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30355','منشار حديد مقفل 12'''' 300 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30365','كاوية لحام',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30367','قرص الصنفرة 5 قطع',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30378','غربال',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30379','مقص العشب',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30382','منقار',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30385','ديسكو جرانيت 7'''' 180 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30390','ديسكو جرانيت 9'''' 230 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30412','مقص بي بي ار',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30413','مقص بي بي ار',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30416','مقص بي بي ار',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30419','عصاة بالة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30436','مسحة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30440','قصدير لحام 30 غ',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10470','لصقة فأر 100غ',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30474','دباسة يدوية',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30475','مقص حدائق',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30488','مفتاح زڨنالي (9 قطع)',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30528','مقص 250 مم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30530','قطن 250 غ',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30533','مفتاح لوندينو 275 مم 11''''  18''''',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30534','مفتاح لوندينو',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30556','فيتي 3.5 * 35 (100غ)',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30571','دادو بالخبوركامل مكيف (34 قطعة)',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30574','ريتي لياسة 20 سم * 10 متر',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30398','قفل نجمة 38 مم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30084','نظارات حماية',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30084','نظارات حماية',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50099','سيفون حوض المطبخ رأس كبير',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10014','مقعد معلق (صندوق خارجي) أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10014','مقعد معلق (صندوق خارجي) أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20024','خلاط دوش كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20024','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10083','خلاط حوض وجه أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10083','خلاط حوض وجه أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80330','مصب دوش بدون تحويلة ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80330','مصب دوش بدون تحويلة ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80180','مخرج شطاف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80180','مخرج شطاف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10014','مجرى 60 سم *6 سم كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20027','علاقة ملابس فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20027','علاقة ملابس فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40031','مسطرة دوش فرديه كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0033','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0033','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80245','كسكاس دوش دائري مع قصبة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80245','كسكاس دوش دائري مع قصبة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30049','رزة باب حديد رقم 10',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10062','مجرى 50 سم *6 سم كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB83067','سماعة دوش مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30086','مرايا حمام مع إضاءة لد 60*60 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30222','سلة قمامة',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10116','مقعد معلق رايملس أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10116','مقعد معلق رايملس أبيض',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10124','حوض وجه معلق -65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10124','حوض وجه معلق -65 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC1111','مثلث كهرباء ثلاث مداخل',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40172','غطاء مقعد تركي أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40172','غطاء مقعد تركي أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10182','سرفنتينة 15 سم * 15 سم مع مانع رائحة كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30740','لقمة جيدور كروم رقم 17',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1755','فسيبلي " 1/2 ذكر * "1/2 أنثى 30سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80771','مخرج شطاف مع علاق ذهبي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10142','طقم اكسسوار أسود',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80215','كسكاس دوش مربع 200*200 مم مع قصبة ذهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80218','كسكاس دوش مربع 200*200 مم مع قصبة ذهبي معا سماعه متحركة مع مخرج شطافة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80219','كسكاس دوش مربع 200*200 مم مع قصبة كروم معا سماعه متحركة مع مخرج شطافة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50155','زر بتارية مقعد سداسي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10169','مسكر زاوية  ''''1/2 * ''''1/2 ذهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80758','مصب دوش قصير بتحويلة كروم',6.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
