-- استيراد المخزون — الجزء 4/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30578','ريتي لياسة 25 سم * 20 متر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30579','ريتي لياسة 25 سم * 20 متر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30610','سلسلة رقم 12 (1متر)',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30611','سلسلة رقم 8 (1متر)',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30368','مقبض باب مع قفل 85 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30390','قفل شنطة 70 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30397','عصاة بالة',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40374','حوض وجه برسلين 80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40375','رف حوض وجه برسلين 80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30375','مرايا حمام مع إضاءة لد 85*85 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50391','رأس سيفوني رخامي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30079','بونتة ترابنو',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30085','فيتي 3 * 30مم 200 قطعة',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50100','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50100','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30023','خلاط حوض المطبخ حائطي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30023','خلاط حوض المطبخ حائطي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20023','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80029','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60033','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10010','خلاط حوض وجه ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MO10011','خلاط حوض المطبخ تحلية كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50023','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50052','خلاط دوش مدفون ثلاثي كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60027','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60030','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80200','طوبو دوش 150سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80003','مصب حوض كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10077','خلاط حوض وجه أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10080','خلاط حوض وجه ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20019','خلاط حوض المطبخ سحاب ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10089','خلاط حوض وجه 3 فتحات كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10089','خلاط حوض وجه 3 فتحات كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20029','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20030','خلاط دوش مع سماعة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10092','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10100','خلاط حوض وجه  كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30011','خلاط شطاف مع شطاف ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30012','خلاط شطاف مع شطاف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30013','خلاط شطاف مع شطاف أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80172','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80176','سماعة خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80181','كسكاس دوش مربع 250*250 مم مع قصبة أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80282','كسكاس دوش مربع 200*200 مم مع قصبة أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80283','كسكاس دوش دائري 250 مم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50026','سيفون حوض الوجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80397','قصبة دوش 40 سم أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80397','قصبة دوش 40 سم أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80199','قصبة دوش مربعة 35 سم ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50394','رأس سيفوني رخامي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30090','حاملة ورق ناعم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10018','مسكر زاوية  ''''1/2 * ''''1/2 اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20125','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20133','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30140','حاملة ورق ناعم زوجية كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30144','حاملة فوط أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30149','حاملة فوط كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30164','خلاط شطاف مع شطاف أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20168','علاقة ملابس فردي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20171','علاقة ملابس زوجية أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20171','علاقة ملابس زوجية أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80248','مخرج شطاف مع علاق ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10185','طقم اكسسوار كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50193','رأس سيفوني ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20042','حاجز دوش 8 مم  مظلم 90  سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80243','مخرج شطاف ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80243','مخرج شطاف ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80202','قصبة دوش  40 سم شبشاشة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80209','قصبة دوش 32 سم أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'TO9047','مفتاح ربط رقم 10 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30045','مفتاح بيبة رقم19مم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10059','مجرى 40 سم *10 سم أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10066','مجرى 30سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10076','سرفنتينة 15 سم * 15 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80240','كسكاس دوش شريحة مربع 250*250 مم مع قصبة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10079','سرفنتينة 15 سم * 15 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AEVE20092','وصلة صرف يمنى رصاصي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AEVE20093','وصلة صرف يسرى رصاصي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30090','مرايا حمام مع إضاءة لد مع اطار دهبي  80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80221','سماعة دوش رصاصي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80222','سماعة دوش رصاصي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30169','حاملة منظفات زوجي كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50995','لامبة لد 50وات',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40101','حوض وجه برسلين مشطوف مع رف 60',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10120','حوض وجه معلق -100 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10123','حوض وجه معلق -75 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10125','حوض وجه معلق -55 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10125','حوض وجه معلق -55 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MF20130','مراية حمام 80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40141','مراية دولاب حمام لد -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30160','مرايا حمام مع إضاءة لد دائرية *3',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30180','أرضية دوش',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80995','كسكاس دوش مربع 300*300 مم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80270','مصب دوش مع تحويلة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20122','علاقة مناشف كروم معا دفاية',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50184','رجسترو مقعد أرضي مائل 7 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30192','حوض مطبخ جرانيت أسود 80*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30194','حوض مطبخ جرانيت بيج  80*50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30195','حوض مطبخ جرانيت رملي محبب 90*50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30202','أرضية دوش 71×36 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30203','أرضية دوش 71×36 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20205','علاقة مناشف مع قاعدة كروم لامع',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0229','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10124','غطاء غرفة تفتيش 30*30 مخفي SUS304',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10125','غطاء غرفة تفتيش 40*40مخفي SUS304',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30835','يد جيدور متحركة ممتازه كريكيتوا',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30735','وصلة جيدور 3قطع في كرت اصفر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50139','رأس سيفوني كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10777','مقعد معلق رايملس أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10777','مقعد معلق رايملس أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20152','علاقة ملابس خماسية دوران',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50158','مثبت غطاء مقعد ضغط كروم بالوردة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10163','طقم اكسسوار ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50164','مطول خلاط دوش مدفون',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30783','موزع صابون سائل كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10166','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*45 كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30793','سلة قمامة',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50796','رأس سيفوني كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30798','مسند لكبار السن 45 كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80425','مصب دوش بدون تحويله ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20803','مقعد أرضي أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40187','حوض وجه برسلين مشطوف 80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10403','حوض مطبخ ستانلس ستيل منظومة دائري بيانو 304 75*46 كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10403','حوض مطبخ ستانلس ستيل منظومة دائري بيانو 304 75*46 كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50206','زر بتريا كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30216','شفاط ابيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80408','شطاف ظغط مربع مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30418','حوض مطبخ جرانيت بيج محبب 55*44',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30418','حوض مطبخ جرانيت بيج محبب 55*44',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30222','مرايا حمام مع إضاءة لد اطار ابيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50423','رأس سيفوني أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50427','سيفون حوض الوجه ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10428','طقم اكسسوار ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10441','خلاط حوض وجه شجرة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10442','خلاط حوض المطبخ شجرة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80445','مصب دوش طويل بتحويلة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80445','مصب دوش طويل بتحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80454','شطاف ظغط دائري مع طوبو أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20455','حاجز دوش 8 مم  مخطط 80*190  سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20457','حاجز دوش 8 مم  مخطط 90*190  سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10258','طقم اكسسوار كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20488','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20489','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20490','علاقة مناشف زوجية بالعلاقة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10288','مانع رائحة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10288','مانع رائحة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30515','حاملة ورق ناعم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0541','دولاب حمام أرضي 60',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10283','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30543','خلاط حوض المطبخ حائطي كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20289','حاجز دوش 8 مم بالعلاقة المناشف80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30293','حوض مطبخ جرانيت أبيض  80*50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80694','يد خلاط  مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30302','فرشة مرحاض كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10596','مقعد معلق رايملس أبيض',-4.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WS10596','مقعد معلق رايملس أبيض',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10597','حوض وجه معلق أبيض -60سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10597','حوض وجه معلق أبيض -60سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20615','خلاط حوض المطبخ سحاب أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40631','مسطرة دوش زوجية مع خلاط دجتل رصاصي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40631','مسطرة دوش زوجية مع خلاط دجتل رصاصي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10644','مجرى 40 سم *8 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80657','شطاف ظغط مربع مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30668','رف زاوية زوجي اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0699','دولاب حمام مع حوض وجه 60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0699','دولاب حمام مع حوض وجه 60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80709','رقبة خلاط متحركة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80329','كسكاس دوش مربع 400*400 مم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30345','مضخة 1/2 حصان',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10331','متبت صليبة المتفوق',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80791','وجه خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80791','وجه خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ADOU50727','كرسي دوش بالظهر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30728','حوض مطبخ جرانيت أبيض  80*50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30729','حوض مطبخ جرانيت أبيض  60*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80377','مخرج شطاف مع علاق كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30384','مضخةرش مبيد حشري 2لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30399','فرشة طلاء ايطالية رقم 50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30406','صابونية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'BAI10402','حوض استحمام بانيو 150*70*53 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80437','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0802','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10803','حوض وجه-80 سم أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10804','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10862','خلاط حوض المطبخ شجرة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50867','رأس سيفوني اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10873','حوض وجه معلق -75 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30758','مفك موجب',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20875','خلاط حوض المطبخ سحاب أسود- كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20875','خلاط حوض المطبخ سحاب أسود- كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10878','مقعد معلق أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30428','رف زاوية زوجي اسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10810','طقم اكسسوار كروم الامونيوم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10897','خلاط حوض وجه شاشة لاد كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10897','خلاط حوض وجه شاشة لاد كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20887','حاجز 8 مم اطار ذهبي 80  سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20887','حاجز 8 مم اطار ذهبي 80  سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20914','حاجز دوش 8 مم  مضبب70  سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20918','حاجز دوش 8 مم  مضبب80  سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40939','حوض كواريون كوارتز 100سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40940','رف كواريون كوارتز 100سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0739','دولاب حمام مع حوض وجه 80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10742','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30747','مرايا حمام مع إضاءة لد',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40753','مسطرة دوش زوجية اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30756','مجفف يد أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30775','مرايا حمام مع إضاءة لد 60*80 سم عرض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10753','طقم اكسسوار كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50758','خلاط دوش مدفون مربع ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA36446','فيتي بالخبور10مم (50 قطعة)',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80827','مصب دوش-مربع بدون تحويلة ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80828','كسكاس دوش مربع  200 مم مع قصبة ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30449','صندوق عدة بلاستك رقم13',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30460','حوض قدم مستطيل اكريليك 70*70 زاوية',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30460','حوض قدم مستطيل اكريليك 70*70 زاوية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80775','مخرج شطاف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80951','كسكاس دوش مربع شريحه 250 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80951','كسكاس دوش مربع شريحه 250 مم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30481','لصقة مع مجفف 400 مل',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30499','مرايا حمام مع إضاءة لد 80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80776','يد خلاط  مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20786','حاجز دوش 10مم اطار كروم مضبب 90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20791','علاقة مناشف زوجية كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80798','كسكاس دوش مربع سميك 25*25 مم مع قصبة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0800','دولاب حمام مع إضاءة لد -90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10801','حوض وجه معلق -90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30802','مرايا حمام مع إضاءة لد 90*70 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10818','مقعد معلق كبير بلس سايز ملحوم تورنيدو أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10818','مقعد معلق كبير بلس سايز ملحوم تورنيدو أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0828','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10826','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10825','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30826','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0839','حوض وجه مع دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0849','حوض وجه مع دولاب حمام -60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30877','حوض مطبخ جرانيت بيج80*50 فردي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30877','حوض مطبخ جرانيت بيج80*50 فردي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30879','حوض مطبخ جرانيت بيج50*43 فردي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10884','حوض مطبخ ستانلس ستيل   65*45 أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10932','حوض مطبخ ستانلس ستيل تحت الرخامة 304 75*44 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0951','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10952','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31020','مرايا حمام مع إضاءة لد 60*80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB11025','خزانة حمام مقبض أسود 120*23*20',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21032','حاجز دوش 70*190سم 8مم اطار كروم مخطط',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE11035','سخانة مربعة   30 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81042','اكسسوار خلاط دوش مدفون دائري ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81043','اكسسوار خلاط شطاف مدفون دائري ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81044','اكسسوار خلاط شطاف مدفون دائري كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81045','اكسسوار خلاط دوش مدفون دائري كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA41050','غطاء مقعد معلق تورنيدو أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA41058','غطاء مقعد معلق تورنيدو أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0559','حوض وجه مع دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10577','حوض وجه معلق80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA21065','سنيسكا 25" كروم مربع',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC51080','زر بتريا أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11083','حوض وجه معلق 85*38سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31085','حاملة ورق ناعم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11091','خلاط حوض وجه أبيض-كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21112','حاجز دوش 10مم اطار كروم منقط 80سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81126','شطاف ظغط مربعة مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31136','مرايا حمام مع إضاءة لد 80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG41137','حوض معا رف كوارتز80سم أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10003','خلاط حوض وجه أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10007','خلاط حوض وجه طويل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10007','خلاط حوض وجه طويل كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80015','قصبة دوش مربعة 40 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80015','قصبة دوش مربعة 40 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10021','خلاط حوض وجه طويل كروم مطفي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10023','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10039','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10039','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20007','خلاط دوش أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30069','خلاط شطاف مع شطاف دائري ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20014','خلاط حوض المطبخ سحاب أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30021','خلاط حوض المطبخ حائطي كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60049','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60049','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80095','مصب دوش بدون تحويلة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80113','قصبة دوش 28 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80124','مخرج شطاف مع علاق كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80126','مخرج شطاف مع علاق كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80130','قصبة دوش 30 سم سقفية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80133','قصبة دوش 35 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80134','قصبة دوش مربعة 35 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50822','خلاط دوش مدفون ايدج ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50822','خلاط دوش مدفون ايدج ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60147','خلاط شطاف مدفون ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60147','خلاط شطاف مدفون ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10181','حوض وجه معلق أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10181','حوض وجه معلق أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50198','سيفون حوض المطبخ',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50198','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50216','بتارية مقعد أرضي تحت',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30249','حوض مطبخ جرانيت رصاصي محبب 90*50',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30253','حوض مطبخ جرانيت رصاصي محبب 80*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30253','حوض مطبخ جرانيت رصاصي محبب 80*50',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10261','سخانة 30 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10261','سخانة 30 لتر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40269','مراية حمام بالدولاب أبيض عتيق  -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10270','مجرى 50 سم *7 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10292','مسكر زاوية  ''''1/2 * ''''3/8 مع وردة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10292','مسكر زاوية  ''''1/2 * ''''3/8 مع وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80303','شطاف ظغط مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50314','صندوق طرد مدفون بتارية مع زر مربع 9 لتر',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40315','حوض وجه برسلين مشطوف 80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40315','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80321','مخرج شطاف أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80321','مخرج شطاف أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40358','رف حوض وجه برسلين 65 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40358','رف حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80005','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80369','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10448','سرفنتينة 15 سم * 15 سم أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10008','سرفنتينة 15 سم * 15 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10009','سرفنتينة 15 سم * 15 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10009','سرفنتينة 15 سم * 15 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10007','مقعد معلق أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20041','خلاط حوض المطبخ سحاب دهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20041','خلاط حوض المطبخ سحاب دهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30037','طلاء مائي داخلي 18 كغ أبيض مطفي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30043','طلاء زيتي 700 غ أَحْمَر لامع',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30045','طلاء زيتي 700 غ رصاصي لامع',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10007','حوض مطبخ ستانلس ستيل   304',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30011','استوك سيارات فايبر  1.9 كغ',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30012','رف زاوية كروم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30012','رف زاوية كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30013','حامل منضفات كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30036','مجفف شعر أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30050','طوبو رش 3/4 20 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30051','طوبو رش 3/4 10 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30075','مجفف يد أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30076','مجفف يد أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30097','ملعقة 7" 18سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30103','صندوق عدة حديد 53 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30105','مضخة 1 حصان',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30111','بدل كورة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30113','بدل كورة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30114','بدل كورة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30120','رأس قفل  7 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30138','مكنسة 60 سم',3.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
