-- استيراد المخزون — الجزء 3/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20458','حاجز دوش 8 مم  مخطط 90*190  سم أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20470','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50472','بتارية مقعد أرضي جنب',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20484','علاقة مناشف زوجية أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20259','علاقة ملابس فردي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50262','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80963','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30502','مرايا حمام مع إضاءة لد اطاركروم 55 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30511','فرشاة تنظيف مرحاض رصاصي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30513','موزع صابون سائل كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20514','علاقة ملابس فردي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50517','رأس سيفوني كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30518','مرايا حمام مع إضاءة لد 50*70 سم اطار اكريلك',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20525','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20531','علاقة مناشف زوجية أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30535','مرايا حمام مع إضاءة لد 80*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50279','خلاط دوش مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60280','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10285','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10546','سخانة 80 لتر افقية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30565','حوض مطبخ جرانيت أسود محبب  47.5*47.5',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30567','حوض مطبخ جرانيت رصاصي محبب  47.5*47.5',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80575','طوبو دوش ألماني كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30576','حوض قدم خزف مربع 60*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40294','حوض رخامي كوارتز 80سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40295','رف رخامي كوارتز 80سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30303','مرايا حمام مع إضاءة لد 60*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80307','كسكاس دوش مربع 200*200 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30580','حوض قدم مستطيل اكريليك 120*80',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'BAI10582','حوض استحمام بانيو برشلونة 190*90سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30583','حوض قدم مستطيل فلات 120*70سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30584','حوض قدم مستطيل فلات 150*70سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80351','شطاف ظغط دائرية مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30585','حوض قدم مستطيل شريحة 120*80سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30586','حوض قدم مستطيل شريحة 100*80سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20588','مقعد أرضي ملحوم أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20588','مقعد أرضي ملحوم أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30593','مرايا حمام مع إضاءة لد دائرية 60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40609','رف رخامي كوارتز 60*50سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30610','مرايا حمام مع إضاءة لد 60*50 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10649','طقم اكسسوار كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40700','مراية دولاب حمام 60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30703','مضخة ماجن 0.8 حصان بالأوتوماتك',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30704','مضخة ماجن 0.8 حصان بالعوامة',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30315','استوك 20 كغ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30328','طلاء مائي داخلي 18 كغ لاتكس',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30706','سلة قمامة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0333','دولاب حمام 80 سم أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0334','حوض وجه  دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40335','مراية دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10336','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80722','كسكاس دوش دائري 300 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ADOU50728','كرسي دوش بدون ظهر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50372','زر بتريا ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30746','مرايا حمام مع إضاءة لد-عرض60*80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30746','مرايا حمام مع إضاءة لد-عرض60*80 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB87399','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30409','حاملة فوط كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10764','خلاط حوض وجه أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10775','خلاط حوض المطبخ شجرة نص منظومة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40780','غطاء مقعد أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80438','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30788','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30793','مرايا حمام ضد البخار مع إضاءة لد 70*50 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30795','مرايا حمام ضد البخار مع إضاءة لد 60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30798','مرايا حمام ضد البخار مع إضاءة لد 80*60 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30798','مرايا حمام ضد البخار مع إضاءة لد 80*60 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80808','كسكاس دوش دائري كبير شلال مع قصبة ملحومة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80811','مصب دوش مربع قصير بالتحويله أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50809','سيفون حوض الوجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10814','طقم اكسسوار كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0827','مطول 1/2 *10 سم نحاسي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10843','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0845','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10865','حوض مطبخ ستانلس ستيل   304 76 *50.5 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1868','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10880','مقعد معلق أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10886','مجرى 60 سم *5 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10889','طقم اكسسوار كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30892','مرايا حمام مع إضاءة لد-عرض60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0901','دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40902','حوض رخامي كوريان 80سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30903','مرايا حمام مع إضاءة لد 60*80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20923','علاقة ملابس رباعية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30941','مرايا حمام مع إضاءة لد 60*100 سم عرض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0738','دولاب حمام مع حوض وجه 60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30749','مرايا حمام مع إضاءة لد',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10788','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30747','خلاط شطاف كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50756','خلاط دوش مدفون أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80800','مصب دوش بدون تحويلة أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80801','كسكاس دوش دائري 200 مم مع قصبة أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50757','خلاط دوش مدفون ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80802','مصب دوش بدون تحويلة ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80803','كسكاس دوش دائري 200 مم مع قصبة ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10759','حوض وجه معلق -100 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50760','خلاط دوش مدفون ايدج ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30458','حوض قدم مستطيل اكريليك 90*90 زاوية',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'BAI10461','حوض استحمام بانيو 150*70*53 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80766','شطاف ظغط مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80467','شطاف ظغط مربع مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80481','قصبة دوش 40 سم سقفية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30475','شفاط ابيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30494','مرايا حمام مع إضاءة لد 100*80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10767','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10770','حوض مطبخ ستانلس ستيل 304 78*43',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20777','علاقة ملابس فردية أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80795','كسكاس دوش دائري 250*250 مم مع قصبة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40795','حوض كواريون كوارتزأبيض 60سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10803','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0805','دولاب حمام مع إضاءة لد-80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10806','حوض وجه معلق -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0810','دولاب حمام مع إضاءة لد-100 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0810','دولاب حمام مع إضاءة لد-100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10811','حوض وجه معلق -100 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10811','حوض وجه معلق -100 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30814','مرايا حمام مع إضاءة لد85*70 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30814','مرايا حمام مع إضاءة لد85*70 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30823','مرايا حمام مع إضاءة لد 100*70 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10836','طقم اكسسوار كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10841','خزانة حمام أبيض',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10841','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0857','دولاب حمام -60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10845','حوض وجه معلق -60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30865','مرايا حمام مع إضاءة لد-عرض60*100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30881','حوض مطبخ جرانيت أسود مطفي78*50 فردي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40918','غطاء مقعد معلق كبير تورنيدو أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40931','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50540','صندوق بتارية مقعد أرضي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80984','مسكر شطافة "1/2" * "1/2 كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40987','حوض كواريون كوارتز80سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40988','رف كواريون كوارتز 80سم أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM51001','سيفون حوض الوجه كلك بمانع رائحة',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE11002','سخانة 50 لتر أفقية',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81016','علاقة سماعة دوش جانبية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG41018','حوض رخامي كوريان 80سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM1019','دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21023','حاجز دوش 80* 190سم 8مم اطار كروم مخطط',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21031','حاجز دوش 60*190سم 8مم اطار كروم مخطط',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81040','اكسسوار خلاط دوش مدفون دائري أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81041','اكسسوار خلاط شطاف مدفون دائري أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA41053','غطاء مقعد معلق تورنيدو أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA41056','غطاء مقعد معلق تورنيدو أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11062','عمود حوض وجه سفير معلق أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31073','حاملة فرشاة أسنان كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31074','صابونية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21113','حاجز دوش 10مم اطار كروم منقط 90سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31122','رف زاوية زوجي كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10000','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10000','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10008','خلاط حوض وجه أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80014','كسكاس دوش دائري 250 مم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80014','كسكاس دوش دائري 250 مم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10019','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10035','خلاط حوض وجه مزخرف طويل أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10035','خلاط حوض وجه مزخرف طويل أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10037','خلاط حوض وجه طويل ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10037','خلاط حوض وجه طويل ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10046','خلاط حوض وجه طويل كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10053','خلاط حوض وجه قصير مربع أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10053','خلاط حوض وجه قصير مربع أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20001','خلاط دوش مع سماعة أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30065','خلاط شطاف مع شطاف أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30067','خلاط شطاف مع شطاف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80072','شطاف ظغط مربع مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80082','شطاف ظغط مربع مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20100','خلاط حوض المطبخ سحاب كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40105','مسطرة دوش زوجية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40111','مسطرة دوش زوجية مع خلاط دجتل أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40114','مسطرة دوش لاد مع خلاط ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20127','خلاط حوض المطبخ سحاب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10003','خلاط حوض المطبخ شجرة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10005','خلاط حوض المطبخ تحلية شجرة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60024','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60026','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50027','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50028','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20030','خلاط حوض المطبخ سحاب أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20032','خلاط حوض المطبخ سحاب أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60038','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50045','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80053','كسكاس دوش مربع 300*300 مم مع قصبة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80062','كسكاس دوش مربع 200*200 مم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80103','مصب دوش مع تحويلة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80111','قصبة دوش مربعة 42 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80114','قصبة دوش 20 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80120','قصبة دوش 40 سم سقفية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80132','قصبة دوش مربعة 30 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80137','قصبة دوش دائري 30 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80137','قصبة دوش دائري 30 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80142','مسكر شطافة دبل "1/2" * "1/2 كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20157','مقعد أرضي ملحوم موطو أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10164','مقعد معلق رايملس أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20178','مقعد أرضي ملحوم ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10189','حوض وجه معلق -65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20197','مقعد أرضي أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50200','سيفون حوض المطبخ',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10202','حوض وجه معلق -60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10202','حوض وجه معلق -60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20211','حوض وجه مربع  فوق الرخام - 46*46سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20211','حوض وجه مربع  فوق الرخام - 46*46سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20212','حوض وجه دائري حوض فوق الرخام - 46سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50213','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50213','سيفون حوض المطبخ',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40226','مراية دولاب حمام -70 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40226','مراية دولاب حمام -70 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30250','حوض مطبخ جرانيت أسود محبب 90*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10264','سخانة 50 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10265','سخانة 80 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40272','مراية حمام بالدولاب خشبي داكن  -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50275','رأس سيفوني كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30286','مرايا حمام مع إضاءة لد مع اطار أبيض 80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30301','خلاط شطاف أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40319','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40319','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40323','حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40324','حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40330','حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40332','حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40342','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40342','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40347','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40347','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40348','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40348','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40355','رف حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40357','رف حوض وجه برسلين 65 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0363','وردة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0002','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80367','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80371','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80375','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40391','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40391','حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40392','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40392','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50400','سيفون حوض الوجه 25سم 30سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50400','سيفون حوض الوجه 25سم 30سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50402','سيفون حوض الوجه كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50404','سيفون حوض الوجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0407','حوض وجه مع دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30408','مرايا حمام مع إضاءة لد 80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10409','خزانة حمام 120*24*20',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1430','فسيبلي " 1/2 ذكر * "1/2 أنثى 50سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0002','دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0002','دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MF20003','مراية حمام 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MF20003','مراية حمام 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20473','علاقة مناشف مع رف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20475','علاقة مناشف زوجية ألمنيوم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80476','طوبو دوش 150سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10481','مجرى 55سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50003','خلاط دوش مدفون مع مصب وقصبة وكسكاس ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50004','خلاط دوش مدفون مع مصب وقصبة وكسكاس ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50004','خلاط دوش مدفون مع مصب وقصبة وكسكاس ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50008','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30008','موزع صابون سائل خزف',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30008','موزع صابون سائل خزف',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50012','سيفون حوض الوجه ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20042','خلاط حوض المطبخ سحاب اسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20053','خلاط حوض المطبخ سحاب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10047','حوض وجه معلق أبيض 50 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10049','حوض وجه معلق 80 سم أبيض مع خلاط مع سيفوني',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30065','طلاء بخاخ داخلي و خارجي أصفر لامع',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30010','استوك سيارات حديد  1.9 كغ',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20017','علاقة مناشف مع رفين كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30028','رف ستاينلس ستيل كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10038','طقم اكسسوار كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20040','علاقة ملابس سداسية',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20046','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20047','علاقة مناشف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30052','موزع صابون سائل كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20060','كوربة رايحة لسيفون  2"',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10070','طقم اكسسوار',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30072','حاملة ورق منظف كلينكس',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30077','مجفف يد كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20080','علاقة ملابس ثلاثية',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40087','غطاء مقعد سداسي أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40087','غطاء مقعد سداسي أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20009','حوض وجه فوق الرخام أبيض -49سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10011','حوض وجه معلق أبيض 35 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30096','رف زاوية ثلاثي كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30104','صندوق عدة حديد 43 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30108','مضخة ماجن 1/2 حصان ضد التآكل',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30116','مضخة ضغط شبكة صغيرة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30117','مضخة ضغط شبكة كبيرة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30119','ترابنو1500 وات',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30141','سلوم 5 درجات',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30144','سلوم 5 درجات 4.5 متر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40149','حوض وجه برسلين مشطوف 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40149','حوض وجه برسلين مشطوف 80 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40150','رف حوض وجه برسلين 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40150','رف حوض وجه برسلين 80 سم',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30153','مكنسة 60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40155','حوض وجه برسلين مشطوف لد 80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40156','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40156','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30157','منجل',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30208','عدة جيدور 24 قطعة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30209','عدة جيدور 24 قطعة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30211','مقص حديد 36" 910 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50239','سير ربط 7.2 * 300 مم (100 قطعة)',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50241','سير ربط 5.2 * 500 مم (100 قطعة)',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30246','طراحة حديد 40 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30248','ميزان ألمنيوم 50 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30253','ميزان خيط 500 غرام',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30260','رف زاوية زوجي اسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0270','وردة كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60290','ستريتشة 3 متر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60291','ستريتشة 2.32 متر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10314','طقم اكسسوار كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30329','منشار شجر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30346','مفتاح إنجليزي رقم 12',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30349','مفتاح إنجليزي رقم 48',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30369','فرطاسة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30383','كستولة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50401','لصقة 0.13 مم * 50 مم * 25 متر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30408','عجلة باب سحاب  رقم 100',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30441','ديسكو ليزري 9'''' 230 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30442','ديسكو ليزري 7'''' 1800 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30443','ديسكو ليزري 7'''' 1800 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30444','ديسكو ليزري 9'''' 230 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30450','خيط أحذية 200 غ',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30453','مفتاح فرنسي رقم 8',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30459','ليفة مسمار 50 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30466','بونتة جبس (16 قطع)',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30483','موس مع 2 منشار',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30491','مسدس سلكون حراري',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30500','بونتة 18 * 450 مم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PA30558','فيتي بالخبور 8 مم (50 قطعة)',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30558','فيتي بالخبور 8 مم (50 قطعة)',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30563','خبور 12 مم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ACOL30576','ريتي لياسة 20 سم * 20 متر',2.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
