-- استيراد المخزون — الجزء 8/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80430','كسكاس دوش مربع  250*250 مم كروم مع قصبة',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20462','خلاط حوض المطبخ سحاب كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20484','حوض وجه فوق الرخام أبيض 41.5 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20484','حوض وجه فوق الرخام أبيض 41.5 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80255','سماعة دوش مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10520','خلاط حوض وجه  كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10520','خلاط حوض وجه  كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30538','مرايا حمام مع إضاءة لد 100*60 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40540','مسطرة دوش زوجية كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40540','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20547','علاقة مناشف زوجية كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60563','خلاط شطاف مدفون كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60563','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30577','حوض قدم خزف مربع 70*70 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30577','حوض قدم خزف مربع 70*70 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80308','مخرج شطاف كروم بالعلاقة',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10595','مقعد معلق رايملس مموج أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10595','مقعد معلق رايملس مموج أبيض',3.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WS10595','مقعد معلق رايملس مموج أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20666','علاقة مناشف زوجية أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20666','علاقة مناشف زوجية أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60675','خلاط شطاف مدفون كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60675','خلاط شطاف مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10701','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10701','حوض مطبخ ستانلس ستيل منظومة بيانو 304 75*46 كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10332','صليبة بيضاء 2ملي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1720','فسيبلي " 1/2 أنثى * "1/2 أنثى 20سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50380','سيفون حوض المطبخ رأس كبير',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80733','كسكاس دوش مربع 250*250 مم ذهبي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80735','قصبة دوش مربعة 40 سم ذهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50482','سيفون حوض الوجه ذهبي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80772','رشاش دوش ذهبي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB84562','كسكاس دوش مربع 250*250 مم اسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40404','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40404','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30796','مرايا حمام ضد البخار مع إضاءة لد 80*100 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80812','مخرج شطاف دائري بالعلاقة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80812','مخرج شطاف دائري بالعلاقة أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30811','حوض مطبخ جرانيت أبيض   80*50',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30414','رأس غاز بلاستك',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1936','فسيبلي خلاط سحاب',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10744','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10744','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20759','علاقة ملابس سداسية',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10784','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10784','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10791','خلاط حوض وجه طويل ذهبي',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20792','خلاط دوش كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30124','كولة 118 مل',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50762','سيفون حوض المطبخ رأس صغير',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80478','قصبة دوش 40 سم سقفية اسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80478','قصبة دوش 40 سم سقفية اسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30492','طلاء عاز ل مطاطي  15 كغ اكسترا',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30485','مجفف شعر أسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40768','مسطرة دوش فرديه كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30510','قفل باب رئيسي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30501','حامل ورق منظف كلينكس',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20511','علاقة ملابس رباعية',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20512','علاقة ملابس ثلاثية',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20524','علاقة ملابس خماسية',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30518','صابونية كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40787','مسطرة دوش زوجية دهبي',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20521','علاقة ملابس زوجية',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0523','وردة كروم',11.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0523','وردة كروم',-5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10835','طقم اكسسوار أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10835','طقم اكسسوار أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30878','حوض مطبخ جرانيت أسود مطفي50*43 فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30878','حوض مطبخ جرانيت أسود مطفي50*43 فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10901','حوض مطبخ ستانلس ستيل منظومة بيانو 304 80*46 أسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10930','سخانة عمودية   50 لتر',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10930','سخانة عمودية   50 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10934','حوض مطبخ ستانلس ستيل   304 تحت الرخامة 76.2*40*22سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10934','حوض مطبخ ستانلس ستيل   304 تحت الرخامة 76.2*40*22سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30542','كولة 500 مل',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10994','خلاط حوض وجه كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30995','خلاط شطاف كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20996','خلاط دوش مع سماعة كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20546','علاقة مناشف كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20549','علاقة مناشف كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20551','علاقة مناشف زوجية بالعلاقة كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10552','خلاط حوض وجه  كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10553','خلاط حوض وجه  كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10554','خلاط حوض وجه اسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81097','شطاف ظغط دائري مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31104','حاملة فوط كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31105','صابونية كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21111','حاجز دوش 10مم اطار كروم منقط 70 سم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD21111','حاجز دوش 10مم اطار كروم منقط 70 سم',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21121','علاقة مناشف كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81125','شطاف ظغط دائرية مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81144','شطاف ظغط ايطالية بلاستك',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81145','شطاف ظغط ايطالية بلاستك',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10054','خلاط حوض وجه دائري أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10054','خلاط حوض وجه دائري أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80081','شطاف ظغط دائري مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80081','شطاف ظغط دائري مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80083','شطاف ظغط دائري مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80083','شطاف ظغط دائري مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50041','خلاط دوش مدفون كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50041','خلاط دوش مدفون كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80106','مصب دوش قصير بدون تحويلة كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80106','مصب دوش قصير بدون تحويلة كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10169','مقعد معلق رايملس أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10169','مقعد معلق رايملس أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10201','حوض وجه معلق -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10201','حوض وجه معلق -80 سم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80260','نبلس خلاط تركي اعتماد مع وردة',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80262','قلب خلاط كبير',-1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80262','قلب خلاط كبير',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80264','مطول فسيبلي خلاط نحاس',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80264','مطول فسيبلي خلاط نحاس',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80296','سماعة دوش مع طوبو أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80296','سماعة دوش مع طوبو أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80304','مخرج شطاف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80304','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1419','فسيبلي " 1/2 أنثى * "1/2 أنثى 20سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1419','فسيبلي " 1/2 أنثى * "1/2 أنثى 20سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10478','مجرى 60سم *7 سم كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10478','مجرى 60سم *7 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20034','سنيسكا 25" كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80700','مخرج شطاف دائري بالعلاقة أسود',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80820','مصب دوش مع تحويلة ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80820','مصب دوش مع تحويلة ذهبي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80822','مصب دوش مع تحويلة أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80822','مصب دوش مع تحويلة أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30021','زمالطو  3 كغ أبيض لامع',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30004','طوبو4'''' 6 متر',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30050','طلاء زيتي 700 غ كريمي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30067','طلاء بخاخ داخلي و خارجي أسود لامع',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30013','كوربة اس (2 قطع) 4" 45°',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10039','طقم اكسسوار كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30043','رف زجاجي كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30044','رف زجاجي كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30044','رف زجاجي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30053','حاملة فوط كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50062','مطول سيفون حوض الوجه كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA40089','غطاء مقعد أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40089','غطاء مقعد أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10097','سرفنتينة 15 سم * 15 سم ذهبي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30112','ماصة 1 كغ',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30121','رأس قفل باب خشب 6 سم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30224','فرشاة حديد',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30252','ميزان 60 سم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30303','صابونية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30303','صابونية كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80356','مصب حوض وجه بدون تحويلة متحرك كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80356','مصب حوض وجه بدون تحويلة متحرك كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30448','خيط لينسة',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30469','فرشاة حديد رأس سكينة',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30531','سلاح ماكينة',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30541','لصقة سريعة (2 قطع)',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30542','مسمارخشب رقم 6 (100غ)',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20394','سنيسكا 25" قصيرة طربوش',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10015','صندوق مقعد معلق أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10015','صندوق مقعد معلق أبيض',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80017','مصب دوش قصير بدون تحويلة كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80140','شطاف ظغط دائري مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80140','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80378','كسكاس دوش مربع 250*250 مم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80380','كسكاس دوش مربع 250*250 مم مع قصبة ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80380','كسكاس دوش مربع 250*250 مم مع قصبة ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80177','مخرج شطاف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80177','مخرج شطاف كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80194','قصبة دوش 40 سم أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80194','قصبة دوش 40 سم أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30048','صابونية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30048','صابونية كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20134','علاقة مناشف متحركة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20134','علاقة مناشف متحركة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AR20046','طلاء مائي داخلي 10 كغ أبيض',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'TO9054','مفتاح ربط رقم11 مم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10061','مجرى 50 سم *7 سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80236','طوبو دوش 150سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30994','عازل ناري 4 كغ',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30097','عصاة رولة',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WA40115','غطاء مقعد تركي أبيض',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80289','مسكر شطافة "1/2" * "1/2 كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80530','طوبو شطاف 1.2 م رصاصي',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80604','مسكر شطافة "1/2" * "1/2 كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80958','شطاف ضغط مربع مع طوبو ذهبي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1779','فسيبلي " 1/2 أنثى * "1/2 أنثى 50سم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50428','سيفون حوض الوجه كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80257','مخرج شطاف ذهبي مع علاقة',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80257','مخرج شطاف ذهبي مع علاقة',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30243','خلاط شطاف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30243','خلاط شطاف كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20246','خلاط دوش أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20246','خلاط دوش أسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10247','خلاط حوض وجه اسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10247','خلاط حوض وجه اسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80464','كسكاس دوش مربع 300*300 مم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20477','مقعد أرضي ملحوم مربع قصير أبيض',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'WP20477','مقعد أرضي ملحوم مربع قصير أبيض',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80586','شطاف ظغط مربع مع طوبو كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20554','مخفض قومه 1.5"',-3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20554','مخفض قومه 1.5"',10.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20555','مخفض قومه 50*26*35 ايطالي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30592','مرايا حمام مع إضاءة لد مربعة 60*80سم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30592','مرايا حمام مع إضاءة لد مربعة 60*80سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10646','مجرى 40 سم *8 سم ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10646','مجرى 40 سم *8 سم ذهبي',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'MC10646','مجرى 40 سم *8 سم ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80658','شطاف ظغط مربع مع طوبو أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80658','شطاف ظغط مربع مع طوبو أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50674','خلاط دوش مدفون شريحة دائري كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50674','خلاط دوش مدفون شريحة دائري كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10685','حوض مطبخ ستانلس ستيل 304 75*45',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10685','حوض مطبخ ستانلس ستيل 304 75*45',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0690','دولاب حمام مع حوض وجه 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0690','دولاب حمام مع حوض وجه 80 سم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM0690','دولاب حمام مع حوض وجه 80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10370','كولة فواصل 001',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB88899','سماعة دوش مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB88899','سماعة دوش مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB87799','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB87799','شطاف ظغط دائري مع طوبو كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80763','مخرج شطاف مع علاق ذهبي',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50776','رأس سيفوني كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30791','مرايا حمام مع إضاءة لد مع بخار 60 اطار أسود',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60806','خلاط شطاف مدفون ميريدا أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60806','خلاط شطاف مدفون ميريدا أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50823','خلاط دوش مدفون شريحة مربع كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20895','خلاط حوض المطبخ سحاب أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20895','خلاط حوض المطبخ سحاب أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80908','كسكاس دوش مربع 300*200 مم مع قصبة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80908','كسكاس دوش مربع 300*200 مم مع قصبة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20932','خلاط حوض المطبخ سحاب كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20932','خلاط حوض المطبخ سحاب كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30750','مرايا حمام مع إضاءة لد',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30750','مرايا حمام مع إضاءة لد',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10786','خلاط حوض وجه كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10786','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20468','سنيسكا 25" اسود مربع',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80792','قصبة دوش دائري 40 سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10520','طقم اكسسوار كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10520','طقم اكسسوار كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50525','زر بتريا أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50525','زر بتريا أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30528','بونتة حديد رقم 3',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30832','سلة قمامة كروم  8 لتر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30832','سلة قمامة كروم  8 لتر',2.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AASB30832','سلة قمامة كروم  8 لتر',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10885','حوض مطبخ ستانلس ستيل   65*45 رصاصي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10885','حوض مطبخ ستانلس ستيل   65*45 رصاصي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10886','حوض مطبخ ستانلس ستيل   60*45 رصاصي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10886','حوض مطبخ ستانلس ستيل   60*45 رصاصي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10800','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10800','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20911','خلاط حوض المطبخ سحاب رصاصي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20911','خلاط حوض المطبخ سحاب رصاصي',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40957','مراية دولاب حمام 70 سم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD21005','خلاط دوش كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81013','مخرج شطاف مع علاق كروم مع مسكر',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81047','وصلة مسطرة دوش40سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30556','خلاط شطاف مع شطاف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30556','خلاط شطاف مع شطاف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11078','خلاط حوض وجه كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81098','شطاف ظغط مربع مع طوبو كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30062','خلاط شطاف مع شطاف كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30062','خلاط شطاف مع شطاف كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80074','شطاف ظغط دائري مع طوبو كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80089','طوبو شطاف 120 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80089','طوبو شطاف 120 سم كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80090','طوبو شطاف 1.2 م أبيض',9.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80090','طوبو شطاف 1.2 م أبيض',-1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80091','يد شطاف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80091','يد شطاف كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80263','قلب خلاط صغير',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80312','مخرج شطاف كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80312','مخرج شطاف كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10471','مجرى 30سم *7 سم كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10471','مجرى 30سم *7 سم كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0002','سرفنتينة 15 سم * 15 سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0002','سرفنتينة 15 سم * 15 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30014','زمالطو ضد الصدأ 3 كغ أبيض مطفي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30018','زمالطو  3 كغ أزرق سماوي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30023','زمالطو 2.5 كغ أَحْمَر لامع',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30031','دهان عازل أكريليكي  كغ3.5 أبيض',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30002','طوبو1.5'''' 6 متر',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30052','طلاء زيتي ضد الصدأ 850 غ أَحْمَر لامع',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30064','طلاء بخاخ داخلي و خارجي كروم لامع',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30007','كوربة 6" 87.5°',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA30025','جرجوري4"',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30025','جرجوري4"',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10042','طقم اكسسوار نحاسي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10042','طقم اكسسوار نحاسي',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20039','علاقة مناشف كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20039','علاقة مناشف كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30102','ملعقة 20سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30130','قادومة 500 غ',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30131','قادومة 300 غ',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30162','سطل بناء',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30250','ميزان 40 سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30251','ميزان 50 سم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30351','مفتاح تي بالمقبض رقم 10',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30352','مفتاح تي بالمقبض رقم 12',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30406','فرشة صاروخ مفتولة  4" 100 مم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30428','ڨوانطي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30493','بونتة 6 * 110 مم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30494','بونتة 8 * 110 مم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20506','طابة نهاية خط حديد 1/2',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20506','طابة نهاية خط حديد 1/2',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50517','لصقة مائية 19مم * 9.1 م',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30523','ترودي 3.25 * 350 مم (1ممØ)',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'FE30526','كسكاس 3/4',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30601','ميزان خيط 500 غرام',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30393','قفل شنطة نحاس 32 مم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50389','رأس سيفوني كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50389','رأس سيفوني كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80018','مصب حوض وجه كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80018','مصب حوض وجه كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80337','مصب دوش مع تحويلة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80337','مصب دوش مع تحويلة كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30049','موزع صابون سائل كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30049','موزع صابون سائل كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0025','حاملة فوط كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0025','حاملة فوط كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10040','حوض مطبخ ستانلس ستيل   304 76*45 سم كروم',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10040','حوض مطبخ ستانلس ستيل   304 76*45 سم كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30197','موزع صابون حساس كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30197','موزع صابون حساس كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'TO9053','مفتاح ربط رقم13 مم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30064','مفك سالب',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40002','مسطرة دوش زوجية كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40002','مسطرة دوش زوجية كروم',7.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80382','سماعة دوش كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80382','سماعة دوش كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50101','لامبة لد 10 وات',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30108','حوض مطبخ جرانيت أبيض محبب 80*50',7.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30108','حوض مطبخ جرانيت أبيض محبب 80*50',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC1113','مثلث كهرباء',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ADOU50186','سيفون حوض قدم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80295','مسكر شطافة "1/2" * "1/2 دهبي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80403','رقبة خلاط متحركة فلتر كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80206','قلب خلاط كبير',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0230','وردة كروم 3/4',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30195','طلاء مائي داخلي 10 كغ أبيض 4% لمعة',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30738','لقمة جيدور كروم رقم 12',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1751','فسيبلي " 1/2 ذكر * "1/2 أنثى 80سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50157','مثبت غطاء مقعد سكة بلستك',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50157','مثبت غطاء مقعد سكة بلستك',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80899','مثبت خلاط شجرة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80899','مثبت خلاط شجرة',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0168','وردة ذهبي دائري',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50288','رأس سيفوني كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50288','رأس سيفوني كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20456','حاجز دوش 8 مم  مخطط 80*190  سم أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20456','حاجز دوش 8 مم  مخطط 80*190  سم أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40542','مسطرة دوش زوجية مع خلاط كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80550','سماعة دوش مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80550','سماعة دوش مع طوبو كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20627','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20627','خلاط دوش كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10651','طقم اكسسوار ذهبي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10651','طقم اكسسوار ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30670','مسند لكبار السن كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30670','مسند لكبار السن كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30672','فرشاة تنظيف مرحاض أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30672','فرشاة تنظيف مرحاض أسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50676','خلاط دوش مدفون كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50676','خلاط دوش مدفون كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20687','علاقة مناشف كبيرة ثلاثية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20687','علاقة مناشف كبيرة ثلاثية كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10330','صليبة بيضاء 2.5ملي',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CC10366','كولة فواصل 033',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80724','قصبة دوش دائري 40 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80724','قصبة دوش دائري 40 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10385','حنفية فردية حائط بلاستك',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80949','شطاف ظغط دائري مع طوبو كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20411','علاقة ملابس فردي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20411','علاقة ملابس فردي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB92416','قصبة دوش 40 سم كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80656','سماعة دوش مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80656','سماعة دوش مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30493','طلاء مائي داخلي 10 كغ أبيض نص لمعة',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MDE50807','خلاط دوش مدفون ميريدا أسود',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MDE50807','خلاط دوش مدفون ميريدا أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40426','مسطرة دوش زوجية كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40426','مسطرة دوش زوجية كروم',6.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10437','غطاء غرفة تفتيش 40*40 فايبر اسود',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80906','سماعة دوش مع طوبو كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80907','كسكاس دوش مربع 300*200 مم مع قصبة أسود',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80907','كسكاس دوش مربع 300*200 مم مع قصبة أسود',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20927','خلاط حوض المطبخ سحاب أسود',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80935','مصب حوض وجه طويل بدون تحويلة كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20732','علاقة مناشف كبيرة بالرف كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20732','علاقة مناشف كبيرة بالرف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20734','علاقة ملابس صبعين كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20761','علاقة ملابس سداسية',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20761','علاقة ملابس سداسية',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML0786','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML0786','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10789','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10789','خلاط حوض وجه كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30465','مرايا حمام مع إضاءة لد مربعة 60*80سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80868','كسكاس دوش مربع 250*250 مم مع قصبة اسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80868','كسكاس دوش مربع 250*250 مم مع قصبة اسود',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RA20470','سنيسكا 25" ذهبي مربع',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20470','سنيسكا 25" ذهبي مربع',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30503','زمالطو  3 كغ أبيض مطفي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SI10509','سلكون حراري استرا اسود 1600c',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SI10509','سلكون حراري استرا اسود 1600c',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50790','رأس سيفوني رخامي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50790','رأس سيفوني رخامي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10817','مقعد معلق ملحوم تورنيدو أبيض',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10817','مقعد معلق ملحوم تورنيدو أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30530','بونتة حديد رقم 8',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30531','بونتة حديد رقم 10',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MA20923','خلاط حوض المطبخ سحاب كروم مطفي',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20923','خلاط حوض المطبخ سحاب كروم مطفي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80938','طوبو شطاف فلتر1.2م رصاصي',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0955','دولاب حمام -70 سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10956','حوض وجه معلق -70 سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10990','مجرى 40 سم *6 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10990','مجرى 40 سم *6 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81010','سماعة دوش مع طوبو كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31021','مرايا حمام ضد البخار لد بالعلاقة اطار وردة كروم70*70سم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81099','شطاف ظغط دائري مع طوبو كروم',8.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10052','خلاط حوض وجه طويل كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10052','خلاط حوض وجه طويل كروم',5.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80135','مصب دوش مع تحويلة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80135','مصب دوش مع تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10168','مقعد معلق رايملس أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10168','مقعد معلق رايملس أسود',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VP20216','حوض وجه فوق الرخام ذهبي -48سم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VP20216','حوض وجه فوق الرخام ذهبي -48سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0258','كوربة ذكر "1/2 * "1/2 مع وردة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0258','كوربة ذكر "1/2 * "1/2 مع وردة كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80339','مسكر شطافة "1/2" * "1/2 كروم',9.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10415','مجرى 75 سم *7 سم كروم',5.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10415','مجرى 75 سم *7 سم كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10001','مجرى شباك  40 سم *8 سم كروم',8.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10001','مجرى شباك  40 سم *8 سم كروم',1.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
