-- استيراد المخزون — الجزء 5/11
begin;
insert into pos_stock (location_id, product_code, product_name, qty, updated_at)
select l.id, v.pc, v.pn, v.q, now()
from (values
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30177','مزيل صدأ 450 مل',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30178','مزيل صدأ 200 مل',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30201','سكينة تغليف 2"',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30212','مقص حديد 30" 750 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30213','مقص حديد 18" 450 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30243','منشار شجر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30247','ميزان ألمنيوم 40 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20263','خلاط حوض المطبخ سحاب كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'P30268','عوامة كهربائية 1 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60283','ستريتشة 2.44 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ASCA60284','ستريتشة 2.44 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10311','طقم اكسسوار كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80322','مسكر شطافة دبل "1/2" * "1/2 كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30356','ديسكو جرانيت 4.5'''' 115 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30374','كستولة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30388','ديسكو خشب 7'''' 180 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50403','لصقة ألمنيوم 5 سم 30 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30404','فرشة صاروخ نحاس  4" 100 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30445','سلكون حراري',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30451','شنطة مسمار',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30454','مفتاح فرنسي رقم 10',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30455','مفتاح فرنسي رقم 12',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30456','ليفة مسمار 70 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30458','ليفة مسمار 60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RO10477','حنفية 1/2',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30478','بينسة رقم 7',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30502','بونتة 22 * 450 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30505','بونتة منقار أفطس',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50519','لصقة خزان 10 سم 5 متر',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30521','ترودي 3.25 * 350 مم (1ممØ)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30546','قفل باب رئيسي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30549','فيتي لاميرة 4.2 * 13 (100غ)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30560','فيتي بالخبور 10 مم (50 قطعة)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30564','فيتي بالخبور 10مم (50 قطعة)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30565','فيتي بالخبور 6مم (100 قطعة)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30609','سلسلة رقم 10 (1متر)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA30619','مقبض باب مع قفل 85 مم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30389','قفل شنطة 40 مم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40369','حوض وجه برسلين مشطوف 80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40369','حوض وجه برسلين مشطوف 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40370','رف حوض وجه برسلين 80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40370','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50392','رأس سيفوني رخامي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50392','رأس سيفوني رخامي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ELC2005','قرجوطة 32مم *25 م',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10076','خلاط حوض وجه ذهبي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10076','خلاط حوض وجه ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10019','حوض مطبخ ستانلس ستيل   304 85*45 كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10019','حوض مطبخ ستانلس ستيل   304 85*45 كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10020','حوض مطبخ ستانلس ستيل   304 86 * 45 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30025','خلاط حوض المطبخ حائطي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30025','خلاط حوض المطبخ حائطي كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MM30026','حنفية حوض المطبخ حائطي كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30026','حنفية حوض المطبخ حائطي كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20017','خلاط حوض المطبخ سحاب كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50018','رأس سيفوني اسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10085','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10085','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10086','خلاط حوض وجه شلال طويل أسود كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10086','خلاط حوض وجه شلال طويل أسود كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10087','خلاط حوض وجه كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10087','خلاط حوض وجه كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20026','خلاط دوش كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20026','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20028','خلاط دوش كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10040','خلاط حوض المطبخ شلال شجرة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10094','خلاط حوض وجه  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10094','خلاط حوض وجه  كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30010','خلاط شطاف مع شطاف أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30010','خلاط شطاف مع شطاف أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80152','شطاف ظغط دائري مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80156','شطاف ظغط دائري مع مخرج شطاف دبل مع طوبو أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80156','شطاف ظغط دائري مع مخرج شطاف دبل مع طوبو أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80171','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30023','خلاط شطاف مع شطاف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80387','كسكاس دوش مربع 240*240 مم مع قصبة أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80387','كسكاس دوش مربع 240*240 مم مع قصبة أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80391','مصب دوش مع تحويلة ابيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80391','مصب دوش مع تحويلة ابيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50028','سيفون حوض الوجه ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80393','قصبة دوش 28 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80393','قصبة دوش 28 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80398','قصبة دوش مربعة 40 سم كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80398','قصبة دوش مربعة 40 سم كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30032','موزع صابون سائل كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30032','موزع صابون سائل كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30055','حاملة فرشاة أسنان زجاجي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30060','صابونية ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30078','حاملة فرشاة أسنان أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20028','علاقة ملابس فردي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50037','رقبة خلاط حوض مطبخ',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30141','حاملة فوط كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30148','حاملة فوط أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80250','مخرج شطاف مع علاق كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50178','زر بتريا كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30190','حاملة فوط كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20043','حاجز دوش 8 مم  مظلم 100  سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20200','علاقة مناشف كبيرة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30150','لصقة دبل فيس 3 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA30015','مفتاح بيبة رقم17مم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10063','مجرى 60سم *7 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10072','سرفنتينة 20*20*28 سم مثلث كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10080','سرفنتينة 15 سم * 15 سم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10085','مجرى 45سم *7 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50071','سيفون حوض الوجه دهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80233','طوبو شطاف 1.2 م رصاصي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80231','طوبو شطاف 120 سم أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL50996','لامبة لد 30وات',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30199','مرايا حمام ضد البخار مع إضاءة لد 60*60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30103','مرايا حمام مع إضاءة لد 80*50سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10114','مقعد معلق رايملس أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10104','سخانة 50 لتر',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CE10104','سخانة 50 لتر',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30127','بونتة صاروخ طاسة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE32118','راس غاز ايطالي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0118','راس غاز',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0118','راس غاز',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VE30152','حوض وجه تحت الرخام أبيض -50سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80997','كسكاس دوش مربع 200*200 مم مع قصبة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10171','خلاط حوض وجه 2 فتحات كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50180','سيفون حوض المطبخ رأس صغير',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50207','مثبت غطاء مقعد',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50209','مثبت صندوق بتارية مقعد أرضي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80405','يد شطاف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50218','مثبت حوض الوجه',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0219','وردة ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0221','وردة كروم 3/4',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50226','طقم تثبيت المرحاض المعلق على الحائط',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AECU50235','رقبة خلاط حوض مطبخ',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB8022','مخرج شطاف مع علاق  كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB8022','مخرج شطاف مع علاق  كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30134','مطول خلاط شطافه مدفون',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MT30134','مطول خلاط شطافه مدفون',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20135','سنيسكا خارجيه دبل كواردة لحام 32',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RFP1759','فسيبلي " 1/2 أنثى * "3/8 أنثى 60سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10763','خلاط حوض وجه  ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20765','علاقة ملابس ثلاثية دوران بدون قصبة',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20766','علاقة ملابس ثلاثية دوران بدون قصبة',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PS20766','علاقة ملابس ثلاثية دوران بدون قصبة',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10138','حوض مطبخ ستانلس ستيل   70*45 كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ABAG50150','سيفون حوض استحمام بانيو',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40161','مسطرة دوش زوجية دهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30799','مسند لكبار السن 60 كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80469','سماعة دوش مع طوبو ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80805','شطاف ضغط دائري مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30807','حامل ورق منظف كلينكس',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40180','حوض وجه برسلين 100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'LG40180','حوض وجه برسلين 100 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40181','رف حوض وجه برسلين 100 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40181','رف حوض وجه برسلين 100 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40188','رف حوض وجه برسلين 80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG40188','رف حوض وجه برسلين 80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PSB10825','دولاب حمام حوض مع مرايا لد -90 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PSB10825','دولاب حمام حوض مع مرايا لد -90 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50205','زر بتريا كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50205','زر بتريا كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80409','مصب دوش بدون تحويلة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SI10412','سلكون  280 غرام شفاف',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80602','مصب دوش بدون تحويلة ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'SA10427','طقم اكسسوار كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30439','خلاط شطاف مع شطاف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40240','مسطرة دوش مع خلاط اسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40240','مسطرة دوش مع خلاط اسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10241','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80465','كسكاس دوش مربع 250*250 مم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MT30469','خلاط شطاف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20478','مقعد أرضي ملحوم ذهبي مخطط',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20478','مقعد أرضي ملحوم ذهبي مخطط',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50260','سيفون حوض الوجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20486','علاقة ملابس خماسية',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10491','حوض وجه معلق -60 * 45 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80272','شطاف ظغط دائري مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MI10264','مراية تجميل مكبرة',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30271','طلاء بخاخ داخلي و خارجي أبيض لامع',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS20532','علاقة مناشف زوجية ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30520','مرايا حمام مع إضاءة لد 100*70 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40284','خلاط حوض وجه مدفون مع مَصَب كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20290','حاجز دوش 8 مم بالعلاقة المناشف90سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20290','حاجز دوش 8 مم بالعلاقة المناشف90سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30566','حوض مطبخ جرانيت أبيض محبب  47.5*47.5',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30566','حوض مطبخ جرانيت أبيض محبب  47.5*47.5',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80574','سماعة دوش كروم مع اضاءة لد',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30292','حوض مطبخ جرانيت رصاصي محبب  80*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30292','حوض مطبخ جرانيت رصاصي محبب  80*50',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WP20587','مقعد أرضي ملحوم أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WP20587','مقعد أرضي ملحوم أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RE10591','حنفية حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RE10591','حنفية حوض المطبخ شجرة كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10595','حوض مطبخ ستانلس ستيل 304 80*45',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10312','حوض وجه معلق 100 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30669','مسند لكبار السن أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30669','مسند لكبار السن أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80681','وجه خلاط شطاف مدفون مربع كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80681','وجه خلاط شطاف مدفون مربع كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10683','خلاط حوض المطبخ شجرة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0692','دولاب حمام مع حوض وجه 60 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0692','دولاب حمام مع حوض وجه 60 سم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM0692','دولاب حمام مع حوض وجه 60 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40694','مراية دولاب حمام 60 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40694','مراية دولاب حمام 60 سم',1.0),
((select id from pos_locations where name ilike '%جنزور%' limit 1),'AM40694','مراية دولاب حمام 60 سم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30705','سلة قمامة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80710','رقبة خلاط متحركة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80711','رقبة خلاط متحركة كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RO10328','حنفية 3/4',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80788','وجه خلاط دوش مدفون اسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80788','وجه خلاط دوش مدفون اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80790','وجه خلاط شطاف مدفون اسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80790','وجه خلاط شطاف مدفون اسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ART0719','متبث مقعد معلق CITY',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ART0719','متبث مقعد معلق CITY',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RFP1374','فسيبلي " 1/2 أنثى * "1/2 أنثى 30سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80736','كسكاس دوش دائري 250 مم ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30407','حاملة فوط كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AASB30407','حاملة فوط كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80786','قصبة دوش مربعة 40 سم اسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80773','قلب خلاط حوض مطبخ شلال',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50777','رأس سيفوني أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30782','حاملة ورق ناعم كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80783','سماعة دوش كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40403','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50785','رأس سيفوني كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30799','مرايا حمام ضد البخار مع إضاءة لد 70*50 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30799','مرايا حمام ضد البخار مع إضاءة لد 70*50 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30805','مرايا حمام مع إضاءة لد 83*63 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80810','مصب دوش مربع قصير بدون تحويله أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80810','مصب دوش مربع قصير بدون تحويله أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40813','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MLE40823','خلاط حوض وجه مدفون مع مَصَب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40823','خلاط حوض وجه مدفون مع مَصَب كروم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0853','حوض وجه مع دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0853','حوض وجه مع دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10854','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10854','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30864','مرايا حمام مع إضاءة لد 80*80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EL10866','حوض مطبخ ستانلس ستيل    تحت الرخامة 304 86 * 44 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30871','رف زاوية زوجي اسود مطفي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10881','حوض وجه فوق الرخام أبيض -40*34 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'DAF0887','دفاية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML10900','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80905','سماعة دوش مايك مائلة مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD20888','حاجز دوش 80* 190 سم8 مم أسود',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PD20888','حاجز دوش 80* 190 سم8 مم أسود',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80914','شطاف ظغط دائري مع طوبو كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80914','شطاف ظغط دائري مع طوبو كروم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80937','قصبة دوش سقفية  40 سم كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10743','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CD40754','مسطرة دوش زوجية اسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30757','مجفف يد ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB8076','سماعة دوش مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'CD40761','مسطرة دوش زوجية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40773','حوض كواريون كوارتز 60سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40774','رف كواريون كوارتز 60سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20793','خلاط دوش كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10793','خلاط حوض وجه أسود',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10747','خلاط حوض وجه  كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40748','رف كواريون كوارتز 80سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40749','حوض كواريون كوارتز80سم أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PA35446','فيتي بالخبور 8 مم (50 قطعة)',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30446','صندوق عدة بلاستك رقم21',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30447','صندوق عدة بلاستك رقم18',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30448','صندوق عدة بلاستك رقم15',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30459','حوض قدم مربع  اكريليك100*100',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30459','حوض قدم مربع  اكريليك100*100',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB30765','فرشاة تنظيف مرحاض أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30763','مرايا حمام مع إضاءة لد 60*60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30464','مرايا حمام مع إضاءة لد مربعة 60*80سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80774','شطاف ظغط مع طوبو كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20471','خلاط حوض المطبخ شلال منظومة نص فل',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30477','شفاط ابيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30478','شفاط خشبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PE30479','شفاط ابيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50765','رأس سيفوني كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30493','مرايا حمام مع إضاءة لد 100*80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30498','مرايا حمام مع إضاءة لد 80*60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30500','مرايا حمام مع إضاءة لد مع اطار أسود 80*60 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML10766','خلاط حوض وجه كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80794','مصب دوش بالتحويلة كروم انحاس',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80794','مصب دوش بالتحويلة كروم انحاس',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'SA10837','طقم اكسسوار كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10838','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10838','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30838','مرايا حمام مع إضاءة لد80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30838','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30840','مرايا حمام مع إضاءة لد80*60 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30840','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM0859','دولاب حمام -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0859','دولاب حمام -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10843','حوض وجه معلق -80 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10843','حوض وجه معلق -80 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB10845','خزانة حمام أبيض',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10845','خزانة حمام أبيض',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30844','مرايا حمام مع إضاءة لد80*60 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ML30844','مرايا حمام مع إضاءة لد80*60 سم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30846','مرايا حمام مع إضاءة لد80*60 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30883','حوض مطبخ جرانيت رصاصي78*50 فردي',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30883','حوض مطبخ جرانيت رصاصي78*50 فردي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EL10887','حوض مطبخ ستانلس ستيل   60*45 أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE10925','سخانة 80 لتر عمودية',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80940','اكسسوار وجه خلاط شطاف مدفون اسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80941','واكسسوار وجه خلاط دوش مدفون اسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10537','حوض وجه السفير معلق60 سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10538','عمود حوض وجه سفير أرضي أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AM40953','مراية دولاب حمام 80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80979','مصب دوش مربع بالتحويله أسود',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80979','مصب دوش مربع بالتحويله أسود',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG40981','حوض كواريون كوارتز100سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG40982','رف كواريون كوارتز 100سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML30989','مرايا حمام مع إضاءة لد-عرض60*80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AB11024','خزانة حمام مقبض أبيض 120*23*20',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'LG41028','حوض مع رف كواريون كوارتز 80سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML31029','مرايا حمام كواريون 48*80سم أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21030','حاجز دوش 100*190سم 8مم اطار كروم مخطط',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WA41049','غطاء مقعد معلق تورنيدو أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11061','عمود حوض وجه سفير معلق أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10558','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40560','مراية دولاب حمام -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10562','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0563','حوض وجه  دولاب حمام -90 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0564','دولاب حمام -90 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40565','مراية دولاب حمام -90 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AB10567','خزانة حمام أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM0568','حوض وجه مع دولاب حمام -80 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AM40569','مراية دولاب حمام -80 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB81071','مصب دوش مع تحويلة ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21075','علاقة ملابس فردية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21076','علاقة مناشف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC51081','زر بتريا ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC51082','زر بتريا مربع ذهبي',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS11084','حوض وجه معلق 65*38سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RA20578','سنيسكا 25" ذهبي دائرية',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'CE11088','سخانة 50 لتر أفقية',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21103','علاقة مناشف زوجية كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PS21108','علاقة مناشف كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PD21110','حاجز دوش 10مم اطار كروم منقط 100 سم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31130','مجفف يد أسود',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'AASB31132','مجفف يد أبيض',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ML11133','خلاط حوض وجه  كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MD20004','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MD20004','خلاط دوش كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80085','شطاف ظغط دائري مع طوبو كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80109','شطاف ظغط مربع مع طوبو ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20118','خلاط حوض المطبخ سحاب ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10130','خلاط حوض المطبخ سحاب كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ME10012','خلاط حوض المطبخ شجرة كروم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ME10012','خلاط حوض المطبخ شجرة كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30010','خلاط حوض المطبخ حائطي كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MM30020','خلاط حوض المطبخ حائطي كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MA20036','خلاط حوض المطبخ سحاب كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MTE60039','خلاط شطاف مدفون كروم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MTE60039','خلاط شطاف مدفون كروم',3.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MLE40042','خلاط حوض وجه مدفون مع مَصَب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MLE40042','خلاط حوض وجه مدفون مع مَصَب كروم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80069','مصب دوش بدون تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80098','مصب دوش بدون تحويلة ذهبي',4.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80104','مصب دوش بدون تحويلة كروم',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'MC10139','سرفنتينة 15 سم * 15 سم ذهبي',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'MC10139','سرفنتينة 15 سم * 15 سم ذهبي',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ARSB80144','كسكاس دوش مربع 250*250 مم ذهبي',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80144','كسكاس دوش مربع 250*250 مم ذهبي',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'WS10172','مقعد معلق رايملس أبيض',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'WS10172','مقعد معلق رايملس أبيض',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'AECU50205','سيفون حوض المطبخ',4.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'VS10205','حوض وجه معلق رصاصي -60سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'VS10205','حوض وجه معلق رصاصي -60سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50208','رجسترومقعد أرضي 40 سم',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50208','رجسترومقعد أرضي 40 سم',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ALVM50211','قرجوطة سيفون حوض الوجه 1.1/4*80 سم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ALVM50211','قرجوطة سيفون حوض الوجه 1.1/4*80 سم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'PLSA0231','مُطوِّل "1/2 * 20 كروم',-2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'PLSA0231','مُطوِّل "1/2 * 20 كروم',6.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'ATWC50245','رجسترو مقعد أرضي مستقيم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ATWC50245','رجسترو مقعد أرضي مستقيم',1.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'EG30252','حوض مطبخ جرانيت أسود  80*50',2.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'EG30252','حوض مطبخ جرانيت أسود  80*50',2.0),
((select id from pos_locations where name ilike '%11 يونيو%' limit 1),'RD30306','حوض قدم خزف مربع 70*70 سم',1.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'RD30306','حوض قدم خزف مربع 70*70 سم',3.0),
((select id from pos_locations where name ilike '%السراج%' limit 1),'ARSB80319','مخرج شطاف ذهبي',4.0)
) as v(lid, pc, pn, q)
join pos_locations l on l.id = v.lid
on conflict (location_id, product_code) do update set qty = excluded.qty;
commit;
