-- ═══ 0016 — إصلاح ترقيم فواتير البيع (عداد مخصص)
-- المصدر (نسخة حرفية بلا تعديل إلا ما يوسم بـ ⚙️ إصلاح سلسلة): apps/pos/benamor-sales-system/supabase-pos-invoice-numbering-fix.sql
-- الترتيب داخل supabase/migrations هو ترتيب التنفيذ المعتمد لقاعدة فارغة

-- Benamor POS - Atomic backend invoice numbering fix
-- Run once in Supabase SQL Editor.
-- Purpose: invoice_no is generated by database trigger, atomically, with unique index.
-- Format: INV-1001, INV-1002, INV-1003...

begin;

create table if not exists public.pos_number_counters (
  key text primary key,
  last_value bigint not null default 0,
  updated_at timestamptz not null default now()
);

create or replace function public.next_pos_invoice_number()
returns text
language plpgsql
security definer
as $$
declare
  n bigint;
  start_value bigint;
begin
  -- Start at the highest existing INV numeric suffix, or 1000 if none exists.
  select greatest(
    1000,
    coalesce(max((regexp_match(invoice_no, '^INV-([0-9]+)$'))[1]::bigint), 1000)
  ) into start_value
  from public.pos_sales
  where invoice_no ~ '^INV-[0-9]+$';

  insert into public.pos_number_counters(key,last_value,updated_at)
  values ('sale_invoice', start_value + 1, now())
  on conflict (key) do update
    set last_value = greatest(public.pos_number_counters.last_value + 1, start_value + 1),
        updated_at = now()
  returning last_value into n;

  return 'INV-' || n::text;
end;
$$;

create or replace function public.trg_pos_sales_invoice_number()
returns trigger
language plpgsql
as $$
begin
  if new.invoice_no is null or trim(new.invoice_no) = '' then
    new.invoice_no := public.next_pos_invoice_number();
  end if;
  return new;
end;
$$;

-- Renumber existing empty invoice numbers.
update public.pos_sales
set invoice_no = public.next_pos_invoice_number()
where invoice_no is null or trim(invoice_no) = '';

-- Renumber existing duplicates before creating unique index.
with d as (
  select id, invoice_no,
         row_number() over(partition by invoice_no order by created_at, id) rn
  from public.pos_sales
  where invoice_no is not null and trim(invoice_no) <> ''
)
update public.pos_sales s
set invoice_no = public.next_pos_invoice_number()
from d
where s.id = d.id and d.rn > 1;

create unique index if not exists pos_sales_invoice_no_uidx
on public.pos_sales(invoice_no)
where invoice_no is not null and trim(invoice_no) <> '';

drop trigger if exists set_pos_sales_number on public.pos_sales;
drop trigger if exists set_pos_sales_invoice_number on public.pos_sales;

create trigger set_pos_sales_invoice_number
before insert on public.pos_sales
for each row execute function public.trg_pos_sales_invoice_number();

commit;
